import type { OsmDrainageLayer } from "./osm";

/**
 * Load the pre-extracted OSM drainage layer for a city.
 *
 * The layer lives under `public/data/` rather than being imported, because a
 * city's drainage geography runs to megabytes and has no business in the client
 * bundle. Generated by `npm run enrich:osm`.
 */
const globalRef = globalThis as typeof globalThis & {
  __floodpilotOsm?: Map<string, OsmDrainageLayer | null>;
};

export async function loadOsmLayer(
  cityId: string,
): Promise<OsmDrainageLayer | null> {
  const cache = (globalRef.__floodpilotOsm ??= new Map());
  if (cache.has(cityId)) return cache.get(cityId) ?? null;

  let layer: OsmDrainageLayer | null = null;

  try {
    // Dynamic imports keep node:fs out of any bundle that does not reach here.
    const [{ readFile }, { join }] = await Promise.all([
      import("node:fs/promises"),
      import("node:path"),
    ]);

    const path = join(process.cwd(), "public", "data", `${cityId}-osm-drainage.json`);
    layer = JSON.parse(await readFile(path, "utf8")) as OsmDrainageLayer;
  } catch {
    // No cache extracted for this city yet. The engine works without it; the
    // source panel reports OSM as unloaded rather than pretending otherwise.
    layer = null;
  }

  cache.set(cityId, layer);
  return layer;
}
