import type { OsmDrainageLayer } from "./osm";

/**
 * Load the pre-extracted OSM drainage layer for a city.
 *
 * The layer lives under `public/data/` rather than being imported, because a
 * city's drainage geography runs to hundreds of kilobytes and has no business in
 * the client bundle. Generated by `npm run enrich:osm`.
 *
 * Two ways to reach it, because serverless platforms disagree about whether
 * static assets exist on a function's filesystem:
 *
 *   1. **Disk.** Works locally and anywhere the file is bundled with the
 *      function. Netlify needs `included_files` in netlify.toml for this.
 *   2. **HTTP.** Fetch it from the deployment's own origin. Slower on a cold
 *      start but always correct, since the file is a public static asset by
 *      definition.
 *
 * If both fail the engine still works — it simply loses the drainage-proximity
 * enrichment, and the source panel reports OSM as unloaded rather than pretending
 * otherwise.
 */
const globalRef = globalThis as typeof globalThis & {
  __floodpilotOsm?: Map<string, OsmDrainageLayer | null>;
};

export async function loadOsmLayer(
  cityId: string,
): Promise<OsmDrainageLayer | null> {
  const cache = (globalRef.__floodpilotOsm ??= new Map());
  if (cache.has(cityId)) return cache.get(cityId) ?? null;

  const layer = (await loadFromDisk(cityId)) ?? (await loadOverHttp(cityId));
  cache.set(cityId, layer);
  return layer;
}

async function loadFromDisk(cityId: string): Promise<OsmDrainageLayer | null> {
  try {
    // Dynamic imports keep node:fs out of any bundle that does not reach here.
    const [{ readFile }, { join }] = await Promise.all([
      import("node:fs/promises"),
      import("node:path"),
    ]);

    const path = join(process.cwd(), "public", "data", `${cityId}-osm-drainage.json`);
    return JSON.parse(await readFile(path, "utf8")) as OsmDrainageLayer;
  } catch {
    return null;
  }
}

async function loadOverHttp(cityId: string): Promise<OsmDrainageLayer | null> {
  const base = deploymentOrigin();
  if (!base) return null;

  try {
    const res = await fetch(`${base}/data/${cityId}-osm-drainage.json`, {
      // Static and immutable between deploys.
      next: { revalidate: 86_400 },
    });
    if (!res.ok) return null;
    return (await res.json()) as OsmDrainageLayer;
  } catch {
    return null;
  }
}

/**
 * The origin this instance is serving from.
 *
 * Each platform names it differently, and none of them is guaranteed, so this
 * returns null rather than guessing when it cannot tell.
 */
function deploymentOrigin(): string | null {
  const explicit = process.env.FLOODPILOT_ORIGIN?.trim();
  if (explicit) return explicit.replace(/\/$/, "");

  // Netlify: DEPLOY_PRIME_URL is the current deploy, URL is the primary domain.
  const netlify = process.env.DEPLOY_PRIME_URL || process.env.URL;
  if (netlify) return netlify.replace(/\/$/, "");

  // Vercel supplies a bare host, not a URL.
  const vercel = process.env.VERCEL_URL;
  if (vercel) return `https://${vercel.replace(/\/$/, "")}`;

  return null;
}
