import type { HotspotRecord } from "../types";

/**
 * Delhi's recurring waterlogging locations.
 *
 * These are the places the city already knows will flood. They exist as *data*,
 * not as branches in the model — the engine reads them as prior evidence and
 * raises the floor on risk, rather than having "if Minto Bridge then flood"
 * written into it anywhere.
 *
 * The list is loaded through `loadHotspots()`, which layers a runtime override on
 * top of this seed, because PWD and DDMA republish their waterlogging-point lists
 * every season and an operator has to be able to update it without a deploy.
 *
 * `verified: true` marks entries corresponding to locations that appear on
 * publicly published civic waterlogging lists. `typicalDepthCm` and
 * `typicalDurationHr` are indicative figures from reported events, not survey
 * measurements.
 */
export const DELHI_HOTSPOTS: HotspotRecord[] = [
  {
    id: "hs_minto_bridge",
    name: "Minto Bridge Underpass",
    at: { lat: 28.636, lng: 77.2205 },
    segmentIds: ["cn_cp_minto"],
    kind: "underpass",
    severity: "chronic",
    typicalDepthCm: 170,
    typicalDurationHr: 14,
    source: "PWD Delhi waterlogging points; Delhi Traffic Police advisories",
    note: "The most photographed flooding point in India. A deep rail underpass with a catchment far larger than its pump capacity — a submerged bus here is an annual news cycle.",
    pumpsDeployed: 4,
    verified: true,
  },
  {
    id: "hs_pul_prahladpur",
    name: "Pul Prahladpur Underpass",
    at: { lat: 28.5042, lng: 77.2833 },
    segmentIds: ["mb_tughlakabad_pulprahladpur"],
    kind: "underpass",
    severity: "chronic",
    typicalDepthCm: 200,
    typicalDurationHr: 22,
    source: "PWD Delhi waterlogging points; DDMA monsoon preparedness review",
    note: "The deepest routine flooding in the city. Water regularly stands above two metres and takes the better part of a day to pump out, cutting the Mehrauli–Badarpur corridor entirely.",
    pumpsDeployed: 6,
    verified: true,
  },
  {
    id: "hs_zakhira",
    name: "Zakhira Underpass",
    at: { lat: 28.6652, lng: 77.1576 },
    segmentIds: ["rr_zakhira_punjabibagh", "rr_motinagar_zakhira"],
    kind: "underpass",
    severity: "chronic",
    typicalDepthCm: 105,
    typicalDurationHr: 17,
    source: "PWD Delhi waterlogging points",
    note: "Sits directly on the Najafgarh drain. When the drain runs at capacity the underpass has nowhere to discharge and fills from the drain rather than from rainfall.",
    pumpsDeployed: 3,
    verified: true,
  },
  {
    id: "hs_azadpur",
    name: "Azadpur Chowk & Underpass",
    at: { lat: 28.7072, lng: 77.1755 },
    segmentIds: ["orr_mukarba_azadpur", "rr_zakhira_azadpur", "nr_azadpur_jahangirpuri"],
    kind: "intersection",
    severity: "chronic",
    typicalDepthCm: 80,
    typicalDurationHr: 13,
    source: "PWD Delhi waterlogging points; MCD desilting reports",
    note: "A major interchange sitting at the confluence of the supplementary drain's catchment. Flooding here paralyses the Outer Ring Road and the GT Karnal Road approach to the city simultaneously.",
    pumpsDeployed: 3,
    verified: true,
  },
  {
    id: "hs_ito",
    name: "ITO Crossing & Tilak Bridge",
    at: { lat: 28.6285, lng: 77.241 },
    segmentIds: ["rr_rajghat_ito", "cn_ito_delhigate", "ey_ito_laxminagar"],
    kind: "arterial_dip",
    severity: "chronic",
    typicalDepthCm: 60,
    typicalDurationHr: 11,
    source: "Delhi Traffic Police advisories; PWD waterlogging points",
    note: "Low ground immediately behind the ITO barrage. Floods from rainfall in an ordinary storm and from the river itself when the Yamuna is above danger level — two different mechanisms at one junction.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_dhaula_kuan",
    name: "Dhaula Kuan Underpass",
    at: { lat: 28.592, lng: 77.161 },
    segmentIds: ["rr_dhaulakuan_naraina", "nh48_dhaulakuan_mahipalpur"],
    kind: "underpass",
    severity: "chronic",
    typicalDepthCm: 55,
    typicalDurationHr: 9,
    source: "PWD Delhi waterlogging points; Delhi Traffic Police advisories",
    note: "The airport corridor's single point of failure. Waterlogging here strands traffic between the city, the airport and Gurugram at the same time.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_najafgarh",
    name: "Najafgarh & Najafgarh Road",
    at: { lat: 28.609, lng: 76.98 },
    segmentIds: ["wd_uttamnagar_najafgarh", "wd_janakpuri_uttamnagar"],
    kind: "drain_overflow",
    severity: "chronic",
    typicalDepthCm: 100,
    typicalDurationHr: 26,
    source: "Delhi I&FC drainage reports; DDMA flood-prone area listing",
    note: "The head of the Najafgarh drain and the lowest point of a very large catchment. Flooding here is drain overflow, not rainfall — it arrives after the rain has stopped and stays for a day.",
    pumpsDeployed: 4,
    verified: true,
  },
  {
    id: "hs_geeta_colony",
    name: "Geeta Colony",
    at: { lat: 28.652, lng: 77.2738 },
    segmentIds: ["ey_rajghat_geetacolony", "ey_geetacolony_laxminagar"],
    kind: "low_colony",
    severity: "chronic",
    typicalDepthCm: 95,
    typicalDurationHr: 30,
    source: "DDMA flood-prone area listing; Delhi I&FC",
    note: "A low-lying trans-Yamuna colony behind the embankment. Depends entirely on the Shahdara drain discharging, which stops the moment the river is high.",
    pumpsDeployed: 3,
    verified: true,
  },
  {
    id: "hs_mukherjee_nagar",
    name: "Mukherjee Nagar",
    at: { lat: 28.7055, lng: 77.2105 },
    segmentIds: ["nr_gtbnagar_mukherjeenagar"],
    kind: "low_colony",
    severity: "chronic",
    typicalDepthCm: 85,
    typicalDurationHr: 16,
    source: "MCD waterlogging complaints; PWD waterlogging points",
    note: "Dense coaching-centre district built over a filled drainage line, with hundreds of occupied basements. The flooding risk here is not to traffic — it is to people below street level.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_ring_road_rajghat",
    name: "Ring Road — Rajghat to Kashmere Gate",
    at: { lat: 28.6406, lng: 77.2494 },
    segmentIds: ["rr_kashmeregate_rajghat", "rr_rajghat_ito", "rr_wazirabad_kashmeregate"],
    kind: "floodplain",
    severity: "chronic",
    typicalDepthCm: 120,
    typicalDurationHr: 60,
    source: "DDMA flood-prone area listing; CWC Yamuna flood records",
    note: "The stretch of Ring Road inside the Yamuna's active floodplain. In July 2023 the river closed it for days — this is river flooding, and it behaves nothing like a cloudburst.",
    verified: true,
  },
  {
    id: "hs_yamuna_floodplain",
    name: "Yamuna Floodplain — Wazirabad to Okhla",
    at: { lat: 28.6575, lng: 77.2497 },
    segmentIds: [
      "ey_wazirabad_signaturebridge",
      "ey_kashmeregate_shastripark",
      "nr_burari_wazirabad",
      "mr_jasola_kalindikunj",
      "ey_pragati_akshardham",
    ],
    kind: "floodplain",
    severity: "chronic",
    typicalDepthCm: 150,
    typicalDurationHr: 90,
    source: "DDMA flood-prone area listing; CWC gauge records at Old Railway Bridge",
    note: "Everything inside the embankments. Governed by the gauge at Old Railway Bridge rather than by local rain, and warned by a Hathnikund release two days earlier.",
    verified: true,
  },
  {
    id: "hs_ashram",
    name: "Ashram Chowk & Underpass",
    at: { lat: 28.573, lng: 77.259 },
    segmentIds: ["rr_saraikalekhan_ashram", "rr_ashram_moolchand"],
    kind: "underpass",
    severity: "chronic",
    typicalDepthCm: 65,
    typicalDurationHr: 12,
    source: "PWD Delhi waterlogging points; Delhi Traffic Police advisories",
    note: "Sits on the Barapullah drain's lower reach. One of the busiest junctions in south Delhi and one of the first to lose its drainage outfall when the river rises.",
    pumpsDeployed: 3,
    verified: true,
  },
  {
    id: "hs_moolchand",
    name: "Moolchand Underpass",
    at: { lat: 28.568, lng: 77.2362 },
    segmentIds: ["rr_ashram_moolchand"],
    kind: "underpass",
    severity: "recurring",
    typicalDepthCm: 50,
    typicalDurationHr: 8,
    source: "PWD Delhi waterlogging points",
    note: "Ring Road underpass beside a major hospital, which makes even a short closure consequential.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_palam_underpass",
    name: "Palam Underpass",
    at: { lat: 28.588, lng: 77.085 },
    segmentIds: ["orr_janakpuri_palam"],
    kind: "underpass",
    severity: "recurring",
    typicalDepthCm: 75,
    typicalDurationHr: 12,
    source: "PWD Delhi waterlogging points",
    note: "Rail underpass on the Outer Ring Road serving the Dwarka and airport approaches.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_okhla_underpass",
    name: "Okhla Underpass",
    at: { lat: 28.556, lng: 77.276 },
    segmentIds: ["mr_okhla_jasola"],
    kind: "underpass",
    severity: "recurring",
    typicalDepthCm: 55,
    typicalDurationHr: 9,
    source: "PWD Delhi waterlogging points",
    note: "Mathura Road underpass with commercial basements alongside.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_karol_bagh",
    name: "Karol Bagh — Pusa Road & Faiz Road",
    at: { lat: 28.6512, lng: 77.19 },
    segmentIds: ["cn_jhandewalan_karolbagh"],
    kind: "basement_parking",
    severity: "recurring",
    typicalDepthCm: 45,
    typicalDurationHr: 7,
    source: "MCD waterlogging complaints",
    note: "Dense market district where nearly every building has a basement. Street depth stays modest; basement losses do not.",
    verified: true,
  },
  {
    id: "hs_rohtak_road_nangloi",
    name: "Rohtak Road — Peeragarhi to Nangloi",
    at: { lat: 28.682, lng: 77.062 },
    segmentIds: ["wd_peeragarhi_nangloi", "wd_punjabibagh_peeragarhi"],
    kind: "drain_overflow",
    severity: "chronic",
    typicalDepthCm: 70,
    typicalDurationHr: 14,
    source: "PWD Delhi waterlogging points; Delhi I&FC drainage reports",
    note: "Runs alongside the Najafgarh drain with ongoing corridor construction narrowing the drainage section.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_vikas_marg",
    name: "Vikas Marg — Laxmi Nagar to Karkardooma",
    at: { lat: 28.6392, lng: 77.2947 },
    segmentIds: ["ey_ito_laxminagar", "ey_laxminagar_preetvihar", "ey_preetvihar_karkardooma"],
    kind: "arterial_dip",
    severity: "recurring",
    typicalDepthCm: 50,
    typicalDurationHr: 9,
    source: "Delhi Traffic Police advisories",
    note: "East Delhi's main artery, dependent on the Shahdara drain. Waterlogging here removes the primary route between east Delhi and the centre.",
    verified: true,
  },
  {
    id: "hs_anand_vihar",
    name: "Anand Vihar",
    at: { lat: 28.6469, lng: 77.3157 },
    segmentIds: ["ey_karkardooma_anandvihar", "ey_anandvihar_gazipur"],
    kind: "intersection",
    severity: "recurring",
    typicalDepthCm: 55,
    typicalDurationHr: 10,
    source: "Delhi Traffic Police advisories; MCD complaints",
    note: "Interstate bus terminal and railway terminal on the same junction; waterlogging strands arriving passengers with no alternative.",
    verified: true,
  },
  {
    id: "hs_loni_road",
    name: "Loni Road — Seelampur to Yamuna Vihar",
    at: { lat: 28.6962, lng: 77.2698 },
    segmentIds: ["ey_seelampur_yamunavihar"],
    kind: "low_colony",
    severity: "recurring",
    typicalDepthCm: 70,
    typicalDurationHr: 16,
    source: "DDMA flood-prone area listing",
    note: "Dense low-lying trans-Yamuna colonies with limited drainage and high population exposure.",
    verified: true,
  },
  {
    id: "hs_sarai_kale_khan",
    name: "Sarai Kale Khan",
    at: { lat: 28.5885, lng: 77.257 },
    segmentIds: ["rr_nizamuddin_saraikalekhan", "rr_saraikalekhan_ashram"],
    kind: "drain_overflow",
    severity: "recurring",
    typicalDepthCm: 60,
    typicalDurationHr: 11,
    source: "PWD Delhi waterlogging points; Delhi I&FC",
    note: "The Barapullah drain's outfall. The first place in south Delhi to show that the river is too high for the city's drains to discharge.",
    pumpsDeployed: 2,
    verified: true,
  },
  {
    id: "hs_mukarba_chowk",
    name: "Mukarba Chowk",
    at: { lat: 28.7292, lng: 77.169 },
    segmentIds: ["orr_mukarba_azadpur", "orr_wazirabad_mukarba"],
    kind: "intersection",
    severity: "recurring",
    typicalDepthCm: 55,
    typicalDurationHr: 10,
    source: "PWD Delhi waterlogging points",
    note: "Where the Outer Ring Road meets GT Karnal Road, on the supplementary drain's catchment.",
    verified: true,
  },
  {
    id: "hs_nehru_place",
    name: "Nehru Place",
    at: { lat: 28.5494, lng: 77.2501 },
    segmentIds: ["orr_chiragdelhi_nehruplace", "sd_nehruplace_kalkaji"],
    kind: "basement_parking",
    severity: "watch",
    typicalDepthCm: 30,
    typicalDurationHr: 5,
    source: "MCD waterlogging complaints",
    note: "Commercial district built as a raised plaza over multi-level basement parking; the risk is what drains downwards, not what stands on the road.",
    verified: false,
  },
];
