import type { SeedSegment } from "@/lib/graph/seed-types";

/**
 * Delhi NCR road network.
 *
 * Each segment carries the four things that decide whether Delhi waterlogs:
 * where it sits relative to the Yamuna floodplain (`floodplain`), which trunk
 * drain it depends on and how far away that drain is (`majorDrainId`,
 * `majorDrainDistanceM`), how well the local storm network performs
 * (`drainQuality`), and whether the road dips below grade (`underpass`).
 *
 * Flood history is an illustrative seed assembled from widely reported
 * waterlogging events. Every record is labelled as seeded in provenance and can
 * be replaced by an authoritative PWD/DDMA incident feed without touching code.
 */
export const DELHI_SEGMENTS: SeedSegment[] = [
  /* ══ Ring Road (Mahatma Gandhi Marg) ═══════════════════════════════════ */
  {
    id: "rr_kashmeregate_rajghat",
    name: "Ring Road · Kashmere Gate → Rajghat",
    corridor: "Ring Road",
    from: "kashmeregate",
    to: "rajghat",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.82,
    drainQuality: 0.38,
    impervious: 0.9,
    floodplain: 0.78,
    majorDrainId: "civillines",
    majorDrainDistanceM: 180,
    exposure: 21_000,
    history: [
      { date: "2023-07-13", depthCm: 96, durationHr: 62, disruptionHr: 70 },
      { date: "2025-07-27", depthCm: 34, durationHr: 9, disruptionHr: 12 },
    ],
    facilities: ["Nigambodh Ghat", "Kashmere Gate ISBT"],
  },
  {
    id: "rr_rajghat_ito",
    name: "Ring Road · Rajghat → ITO",
    corridor: "Ring Road",
    from: "rajghat",
    to: "ito",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.88,
    drainQuality: 0.32,
    impervious: 0.92,
    floodplain: 0.9,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 120,
    pumpStations: 2,
    exposure: 28_000,
    history: [
      { date: "2023-07-13", depthCm: 145, durationHr: 88, disruptionHr: 96 },
      { date: "2024-06-28", depthCm: 42, durationHr: 8, disruptionHr: 14 },
      { date: "2025-07-27", depthCm: 51, durationHr: 11, disruptionHr: 16 },
    ],
    facilities: ["ITO barrage", "Vikas Bhawan", "Delhi Secretariat"],
  },
  {
    id: "rr_ito_pragati",
    name: "Ring Road · ITO → Pragati Maidan",
    corridor: "Ring Road",
    from: "ito",
    to: "pragati",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.76,
    drainQuality: 0.42,
    impervious: 0.91,
    floodplain: 0.6,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 420,
    basementParking: 4,
    exposure: 22_000,
    history: [{ date: "2023-07-13", depthCm: 78, durationHr: 40, disruptionHr: 52 }],
  },
  {
    id: "rr_pragati_nizamuddin",
    name: "Ring Road · Pragati Maidan → Nizamuddin",
    corridor: "Ring Road",
    from: "pragati",
    to: "nizamuddin",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.68,
    drainQuality: 0.5,
    impervious: 0.88,
    floodplain: 0.52,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 650,
    exposure: 18_000,
  },
  {
    id: "rr_nizamuddin_saraikalekhan",
    name: "Ring Road · Nizamuddin → Sarai Kale Khan",
    corridor: "Ring Road",
    from: "nizamuddin",
    to: "saraikalekhan",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.84,
    drainQuality: 0.36,
    impervious: 0.9,
    floodplain: 0.72,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 90,
    pumpStations: 1,
    exposure: 24_000,
    history: [
      { date: "2023-07-13", depthCm: 88, durationHr: 54, disruptionHr: 66 },
      { date: "2024-07-31", depthCm: 39, durationHr: 7, disruptionHr: 11 },
      { date: "2025-07-27", depthCm: 44, durationHr: 9, disruptionHr: 13 },
    ],
    facilities: ["Hazrat Nizamuddin station", "Sarai Kale Khan ISBT"],
  },
  {
    id: "rr_saraikalekhan_ashram",
    name: "Ring Road · Sarai Kale Khan → Ashram",
    corridor: "Ring Road",
    from: "saraikalekhan",
    to: "ashram",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.86,
    drainQuality: 0.34,
    impervious: 0.93,
    floodplain: 0.55,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 240,
    pumpStations: 2,
    exposure: 26_000,
    history: [
      { date: "2023-07-09", depthCm: 62, durationHr: 12, disruptionHr: 18 },
      { date: "2024-06-28", depthCm: 71, durationHr: 14, disruptionHr: 22 },
      { date: "2025-07-27", depthCm: 55, durationHr: 10, disruptionHr: 15 },
    ],
    facilities: ["Ashram underpass"],
  },
  {
    id: "rr_ashram_moolchand",
    name: "Ring Road · Ashram → Moolchand",
    corridor: "Ring Road",
    from: "ashram",
    to: "moolchand",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.74,
    drainQuality: 0.4,
    impervious: 0.91,
    floodplain: 0.2,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 320,
    pumpStations: 1,
    exposure: 19_000,
    history: [
      { date: "2024-06-28", depthCm: 58, durationHr: 9, disruptionHr: 13 },
      { date: "2025-07-27", depthCm: 41, durationHr: 6, disruptionHr: 9 },
    ],
    facilities: ["Moolchand underpass", "Moolchand hospital"],
  },
  {
    id: "rr_moolchand_aiims",
    name: "Ring Road · Moolchand → AIIMS",
    corridor: "Ring Road",
    from: "moolchand",
    to: "aiims",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.54,
    drainQuality: 0.58,
    impervious: 0.87,
    floodplain: 0.05,
    majorDrainId: "kushak",
    majorDrainDistanceM: 700,
    exposure: 17_000,
    facilities: ["AIIMS trauma centre"],
  },
  {
    id: "rr_aiims_safdarjung",
    name: "Ring Road · AIIMS → Safdarjung",
    corridor: "Ring Road",
    from: "aiims",
    to: "safdarjung",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.46,
    drainQuality: 0.62,
    impervious: 0.85,
    floodplain: 0.02,
    exposure: 14_000,
  },
  {
    id: "rr_safdarjung_motibagh",
    name: "Ring Road · Safdarjung → Moti Bagh",
    corridor: "Ring Road",
    from: "safdarjung",
    to: "motibagh",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.44,
    drainQuality: 0.64,
    impervious: 0.83,
    exposure: 13_000,
  },
  {
    id: "rr_motibagh_dhaulakuan",
    name: "Ring Road · Moti Bagh → Dhaula Kuan",
    corridor: "Ring Road",
    from: "motibagh",
    to: "dhaulakuan",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.58,
    drainQuality: 0.56,
    impervious: 0.86,
    exposure: 18_000,
  },
  {
    id: "rr_dhaulakuan_naraina",
    name: "Ring Road · Dhaula Kuan → Naraina",
    corridor: "Ring Road",
    from: "dhaulakuan",
    to: "naraina",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.79,
    drainQuality: 0.38,
    impervious: 0.9,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 1400,
    pumpStations: 1,
    exposure: 25_000,
    history: [
      { date: "2023-07-09", depthCm: 64, durationHr: 11, disruptionHr: 17 },
      { date: "2024-06-28", depthCm: 52, durationHr: 8, disruptionHr: 14 },
      { date: "2025-07-27", depthCm: 47, durationHr: 7, disruptionHr: 11 },
    ],
    facilities: ["Dhaula Kuan interchange", "Airport corridor"],
  },
  {
    id: "rr_naraina_motinagar",
    name: "Ring Road · Naraina → Moti Nagar",
    corridor: "Ring Road",
    from: "naraina",
    to: "motinagar",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.7,
    drainQuality: 0.46,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 900,
    exposure: 16_000,
  },
  {
    id: "rr_motinagar_zakhira",
    name: "Ring Road · Moti Nagar → Zakhira",
    corridor: "Ring Road",
    from: "motinagar",
    to: "zakhira",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.84,
    drainQuality: 0.32,
    impervious: 0.91,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 220,
    exposure: 20_000,
    history: [{ date: "2024-06-28", depthCm: 49, durationHr: 9, disruptionHr: 14 }],
  },
  {
    id: "rr_zakhira_punjabibagh",
    name: "Ring Road · Zakhira → Punjabi Bagh",
    corridor: "Ring Road",
    from: "zakhira",
    to: "punjabibagh",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    underpass: true,
    catchment: 0.91,
    drainQuality: 0.26,
    impervious: 0.92,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 70,
    pumpStations: 2,
    constructionObstruction: true,
    exposure: 27_000,
    history: [
      { date: "2023-07-09", depthCm: 118, durationHr: 20, disruptionHr: 30 },
      { date: "2024-06-28", depthCm: 94, durationHr: 16, disruptionHr: 26 },
      { date: "2025-07-27", depthCm: 82, durationHr: 13, disruptionHr: 21 },
    ],
    facilities: ["Zakhira underpass", "Najafgarh drain crossing"],
  },
  {
    id: "rr_zakhira_azadpur",
    name: "Ring Road · Zakhira → Azadpur",
    corridor: "Ring Road",
    from: "zakhira",
    to: "azadpur",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 50,
    waypoints: [
      { lat: 28.676, lng: 77.172 },
      { lat: 28.694, lng: 77.18 },
    ],
    catchment: 0.86,
    drainQuality: 0.3,
    impervious: 0.9,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 110,
    exposure: 23_000,
    history: [{ date: "2023-07-09", depthCm: 71, durationHr: 13, disruptionHr: 19 }],
  },
  {
    id: "rr_azadpur_wazirabad",
    name: "Ring Road · Azadpur → Wazirabad",
    corridor: "Ring Road",
    from: "azadpur",
    to: "wazirabad",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.82,
    drainQuality: 0.36,
    impervious: 0.88,
    floodplain: 0.62,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 260,
    exposure: 19_000,
    history: [{ date: "2023-07-13", depthCm: 84, durationHr: 46, disruptionHr: 58 }],
  },
  {
    id: "rr_wazirabad_kashmeregate",
    name: "Ring Road · Wazirabad → Kashmere Gate",
    corridor: "Ring Road",
    from: "wazirabad",
    to: "kashmeregate",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.85,
    drainQuality: 0.34,
    impervious: 0.87,
    floodplain: 0.85,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 200,
    exposure: 20_000,
    history: [
      { date: "2023-07-13", depthCm: 132, durationHr: 76, disruptionHr: 90 },
      { date: "2025-07-27", depthCm: 38, durationHr: 8, disruptionHr: 12 },
    ],
    facilities: ["Wazirabad barrage", "Yamuna floodplain"],
  },

  /* ══ Outer Ring Road ═══════════════════════════════════════════════════ */
  {
    id: "orr_wazirabad_mukarba",
    name: "Outer Ring Road · Wazirabad → Mukarba Chowk",
    corridor: "Outer Ring Road",
    from: "wazirabad",
    to: "mukarba",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.78,
    drainQuality: 0.4,
    impervious: 0.87,
    floodplain: 0.5,
    majorDrainId: "supplementary",
    majorDrainDistanceM: 300,
    exposure: 18_000,
  },
  {
    id: "orr_mukarba_azadpur",
    name: "Outer Ring Road · Mukarba Chowk → Azadpur",
    corridor: "Outer Ring Road",
    from: "mukarba",
    to: "azadpur",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.88,
    drainQuality: 0.28,
    impervious: 0.91,
    majorDrainId: "supplementary",
    majorDrainDistanceM: 90,
    pumpStations: 1,
    exposure: 26_000,
    history: [
      { date: "2023-07-09", depthCm: 92, durationHr: 15, disruptionHr: 24 },
      { date: "2024-06-28", depthCm: 76, durationHr: 12, disruptionHr: 20 },
      { date: "2025-07-27", depthCm: 68, durationHr: 11, disruptionHr: 17 },
    ],
    facilities: ["Azadpur mandi", "Azadpur underpass"],
  },
  {
    id: "orr_azadpur_pitampura",
    name: "Outer Ring Road · Azadpur → Pitampura",
    corridor: "Outer Ring Road",
    from: "azadpur",
    to: "pitampura",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.66,
    drainQuality: 0.5,
    impervious: 0.87,
    majorDrainId: "supplementary",
    majorDrainDistanceM: 700,
    exposure: 17_000,
  },
  {
    id: "orr_pitampura_peeragarhi",
    name: "Outer Ring Road · Pitampura → Peeragarhi",
    corridor: "Outer Ring Road",
    from: "pitampura",
    to: "peeragarhi",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.64,
    drainQuality: 0.52,
    impervious: 0.86,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 800,
    exposure: 16_000,
  },
  {
    id: "orr_peeragarhi_janakpuri",
    name: "Outer Ring Road · Peeragarhi → Janakpuri",
    corridor: "Outer Ring Road",
    from: "peeragarhi",
    to: "janakpuri",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.7,
    drainQuality: 0.46,
    impervious: 0.87,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 500,
    exposure: 17_000,
  },
  {
    id: "orr_janakpuri_palam",
    name: "Outer Ring Road · Janakpuri → Palam",
    corridor: "Outer Ring Road",
    from: "janakpuri",
    to: "palam",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.8,
    drainQuality: 0.36,
    impervious: 0.88,
    pumpStations: 1,
    exposure: 19_000,
    history: [
      { date: "2023-07-09", depthCm: 86, durationHr: 14, disruptionHr: 22 },
      { date: "2025-07-27", depthCm: 57, durationHr: 9, disruptionHr: 14 },
    ],
    facilities: ["Palam underpass"],
  },
  {
    id: "orr_palam_dhaulakuan",
    name: "Outer Ring Road · Palam → Dhaula Kuan",
    corridor: "Outer Ring Road",
    from: "palam",
    to: "dhaulakuan",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.56,
    drainQuality: 0.56,
    impervious: 0.85,
    exposure: 15_000,
  },
  {
    id: "orr_dhaulakuan_munirka",
    name: "Outer Ring Road · Dhaula Kuan → Munirka",
    corridor: "Outer Ring Road",
    from: "dhaulakuan",
    to: "munirka",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.42,
    drainQuality: 0.64,
    impervious: 0.84,
    exposure: 16_000,
  },
  {
    id: "orr_munirka_chiragdelhi",
    name: "Outer Ring Road · Munirka → Chirag Delhi",
    corridor: "Outer Ring Road",
    from: "munirka",
    to: "chiragdelhi",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.4,
    drainQuality: 0.66,
    impervious: 0.85,
    exposure: 15_000,
  },
  {
    id: "orr_chiragdelhi_nehruplace",
    name: "Outer Ring Road · Chirag Delhi → Nehru Place",
    corridor: "Outer Ring Road",
    from: "chiragdelhi",
    to: "nehruplace",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.58,
    drainQuality: 0.54,
    impervious: 0.9,
    basementParking: 9,
    exposure: 21_000,
    facilities: ["Nehru Place commercial district"],
  },
  {
    id: "orr_nehruplace_ashram",
    name: "Outer Ring Road · Nehru Place → Ashram",
    corridor: "Outer Ring Road",
    from: "nehruplace",
    to: "ashram",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.66,
    drainQuality: 0.48,
    impervious: 0.89,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 900,
    exposure: 19_000,
  },

  /* ══ NH-48 / Delhi–Gurugram ════════════════════════════════════════════ */
  {
    id: "nh48_dhaulakuan_mahipalpur",
    name: "NH-48 · Dhaula Kuan → Mahipalpur",
    corridor: "NH-48 (Delhi–Gurugram)",
    from: "dhaulakuan",
    to: "mahipalpur",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.44,
    drainQuality: 0.62,
    impervious: 0.86,
    exposure: 22_000,
    facilities: ["Airport approach"],
  },
  {
    id: "nh48_mahipalpur_rajokri",
    name: "NH-48 · Mahipalpur → Rajokri",
    corridor: "NH-48 (Delhi–Gurugram)",
    from: "mahipalpur",
    to: "rajokri",
    roadClass: "highway",
    lanes: 10,
    speedLimitKph: 80,
    catchment: 0.5,
    drainQuality: 0.55,
    impervious: 0.88,
    exposure: 24_000,
    history: [{ date: "2024-06-28", depthCm: 44, durationHr: 6, disruptionHr: 11 }],
  },
  {
    id: "nh48_mahipalpur_igi",
    name: "Airport Road · Mahipalpur → IGI T3",
    corridor: "NH-48 (Delhi–Gurugram)",
    from: "mahipalpur",
    to: "igi",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.4,
    drainQuality: 0.68,
    impervious: 0.84,
    exposure: 16_000,
    facilities: ["IGI Airport Terminal 3"],
  },

  /* ══ Mathura Road (NH-19/44) ═══════════════════════════════════════════ */
  {
    id: "mr_ashram_okhla",
    name: "Mathura Road · Ashram → Okhla",
    corridor: "Mathura Road",
    from: "ashram",
    to: "okhla",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.7,
    drainQuality: 0.46,
    impervious: 0.9,
    floodplain: 0.32,
    exposure: 20_000,
  },
  {
    id: "mr_okhla_jasola",
    name: "Mathura Road · Okhla → Jasola",
    corridor: "Mathura Road",
    from: "okhla",
    to: "jasola",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.78,
    drainQuality: 0.4,
    impervious: 0.9,
    floodplain: 0.48,
    pumpStations: 1,
    basementParking: 6,
    exposure: 21_000,
    history: [{ date: "2024-06-28", depthCm: 61, durationHr: 10, disruptionHr: 15 }],
    facilities: ["Okhla underpass"],
  },
  {
    id: "mr_jasola_saritavihar",
    name: "Mathura Road · Jasola → Sarita Vihar",
    corridor: "Mathura Road",
    from: "jasola",
    to: "saritavihar",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.62,
    drainQuality: 0.52,
    impervious: 0.87,
    floodplain: 0.4,
    exposure: 17_000,
  },
  {
    id: "mr_saritavihar_badarpur",
    name: "Mathura Road · Sarita Vihar → Badarpur",
    corridor: "Mathura Road",
    from: "saritavihar",
    to: "badarpur",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.66,
    drainQuality: 0.5,
    impervious: 0.88,
    exposure: 19_000,
  },
  {
    id: "mr_jasola_kalindikunj",
    name: "Jasola → Kalindi Kunj",
    corridor: "Kalindi Kunj Road",
    from: "jasola",
    to: "kalindikunj",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.86,
    drainQuality: 0.34,
    impervious: 0.82,
    floodplain: 0.88,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 150,
    exposure: 14_000,
    history: [{ date: "2023-07-13", depthCm: 121, durationHr: 68, disruptionHr: 80 }],
    facilities: ["Okhla barrage", "Yamuna floodplain"],
  },
  {
    id: "mr_kalindikunj_noida18",
    name: "Kalindi Kunj → Noida Sector 18",
    corridor: "Kalindi Kunj Road",
    from: "kalindikunj",
    to: "noida18",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.8,
    drainQuality: 0.42,
    impervious: 0.85,
    floodplain: 0.7,
    exposure: 16_000,
  },

  /* ══ Mehrauli–Badarpur Road ════════════════════════════════════════════ */
  {
    id: "mb_saket_tughlakabad",
    name: "MB Road · Saket → Tughlakabad",
    corridor: "Mehrauli–Badarpur Road",
    from: "saket",
    to: "tughlakabad",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.4,
    drainQuality: 0.6,
    impervious: 0.84,
    exposure: 14_000,
  },
  {
    id: "mb_tughlakabad_pulprahladpur",
    name: "MB Road · Tughlakabad → Pul Prahladpur",
    corridor: "Mehrauli–Badarpur Road",
    from: "tughlakabad",
    to: "pulprahladpur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    underpass: true,
    catchment: 0.94,
    drainQuality: 0.22,
    impervious: 0.86,
    pumpStations: 3,
    exposure: 18_000,
    history: [
      { date: "2023-07-09", depthCm: 214, durationHr: 26, disruptionHr: 38 },
      { date: "2024-06-28", depthCm: 168, durationHr: 21, disruptionHr: 32 },
      { date: "2025-07-27", depthCm: 142, durationHr: 18, disruptionHr: 27 },
    ],
    facilities: ["Pul Prahladpur underpass", "Railway underbridge"],
  },
  {
    id: "mb_pulprahladpur_badarpur",
    name: "MB Road · Pul Prahladpur → Badarpur",
    corridor: "Mehrauli–Badarpur Road",
    from: "pulprahladpur",
    to: "badarpur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.72,
    drainQuality: 0.44,
    impervious: 0.85,
    exposure: 15_000,
  },

  /* ══ Aurobindo Marg / South Delhi ══════════════════════════════════════ */
  {
    id: "am_aiims_greenpark",
    name: "Aurobindo Marg · AIIMS → Green Park",
    corridor: "Aurobindo Marg",
    from: "aiims",
    to: "greenpark",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.38,
    drainQuality: 0.66,
    impervious: 0.85,
    exposure: 13_000,
  },
  {
    id: "am_greenpark_hauzkhas",
    name: "Aurobindo Marg · Green Park → Hauz Khas",
    corridor: "Aurobindo Marg",
    from: "greenpark",
    to: "hauzkhas",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.34,
    drainQuality: 0.68,
    impervious: 0.84,
    exposure: 12_000,
  },
  {
    id: "am_hauzkhas_malviyanagar",
    name: "Aurobindo Marg · Hauz Khas → Malviya Nagar",
    corridor: "Aurobindo Marg",
    from: "hauzkhas",
    to: "malviyanagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.32,
    drainQuality: 0.7,
    impervious: 0.83,
    exposure: 12_000,
  },
  {
    id: "am_malviyanagar_saket",
    name: "Aurobindo Marg · Malviya Nagar → Saket",
    corridor: "Aurobindo Marg",
    from: "malviyanagar",
    to: "saket",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.3,
    drainQuality: 0.72,
    impervious: 0.85,
    basementParking: 5,
    exposure: 13_000,
  },
  {
    id: "sd_chiragdelhi_malviyanagar",
    name: "Press Enclave Road · Chirag Delhi → Malviya Nagar",
    corridor: "South Delhi",
    from: "chiragdelhi",
    to: "malviyanagar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.36,
    drainQuality: 0.66,
    impervious: 0.84,
    exposure: 9_000,
  },
  {
    id: "sd_nehruplace_kalkaji",
    name: "Nehru Place → Kalkaji",
    corridor: "South Delhi",
    from: "nehruplace",
    to: "kalkaji",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.5,
    drainQuality: 0.58,
    impervious: 0.88,
    basementParking: 4,
    exposure: 11_000,
  },
  {
    id: "sd_kalkaji_govindpuri",
    name: "Kalkaji → Govindpuri",
    corridor: "South Delhi",
    from: "kalkaji",
    to: "govindpuri",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.64,
    drainQuality: 0.48,
    impervious: 0.88,
    exposure: 12_000,
    history: [{ date: "2024-06-28", depthCm: 43, durationHr: 7, disruptionHr: 10 }],
  },
  {
    id: "sd_govindpuri_okhla",
    name: "Govindpuri → Okhla",
    corridor: "South Delhi",
    from: "govindpuri",
    to: "okhla",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.72,
    drainQuality: 0.42,
    impervious: 0.87,
    exposure: 12_000,
  },
  {
    id: "sd_ashram_lajpatnagar",
    name: "Ashram → Lajpat Nagar",
    corridor: "South Delhi",
    from: "ashram",
    to: "lajpatnagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.62,
    drainQuality: 0.5,
    impervious: 0.89,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 450,
    exposure: 13_000,
  },
  {
    id: "sd_lajpatnagar_moolchand",
    name: "Lajpat Nagar → Moolchand",
    corridor: "South Delhi",
    from: "lajpatnagar",
    to: "moolchand",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.56,
    drainQuality: 0.54,
    impervious: 0.88,
    majorDrainId: "barapullah",
    majorDrainDistanceM: 300,
    exposure: 10_000,
  },
  {
    id: "sd_saket_vasantkunj",
    name: "Saket → Vasant Kunj",
    corridor: "South Delhi",
    from: "saket",
    to: "vasantkunj",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.26,
    drainQuality: 0.74,
    impervious: 0.78,
    exposure: 11_000,
  },
  {
    id: "sd_vasantkunj_munirka",
    name: "Vasant Kunj → Munirka",
    corridor: "South Delhi",
    from: "vasantkunj",
    to: "munirka",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.28,
    drainQuality: 0.72,
    impervious: 0.8,
    exposure: 11_000,
  },
  {
    id: "sd_munirka_vasantvihar",
    name: "Munirka → Vasant Vihar",
    corridor: "South Delhi",
    from: "munirka",
    to: "vasantvihar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.3,
    drainQuality: 0.72,
    impervious: 0.79,
    exposure: 8_000,
  },
  {
    id: "sd_vasantvihar_dhaulakuan",
    name: "Vasant Vihar → Dhaula Kuan",
    corridor: "South Delhi",
    from: "vasantvihar",
    to: "dhaulakuan",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.4,
    drainQuality: 0.66,
    impervious: 0.82,
    exposure: 12_000,
  },
  {
    id: "sd_motibagh_rkpuram",
    name: "Moti Bagh → RK Puram",
    corridor: "South Delhi",
    from: "motibagh",
    to: "rkpuram",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.36,
    drainQuality: 0.68,
    impervious: 0.8,
    exposure: 8_500,
  },
  {
    id: "sd_rkpuram_munirka",
    name: "RK Puram → Munirka",
    corridor: "South Delhi",
    from: "rkpuram",
    to: "munirka",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.34,
    drainQuality: 0.7,
    impervious: 0.8,
    exposure: 8_000,
  },
  {
    id: "sd_sarojini_safdarjung",
    name: "Sarojini Nagar → Safdarjung",
    corridor: "South Delhi",
    from: "sarojini",
    to: "safdarjung",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.42,
    drainQuality: 0.64,
    impervious: 0.85,
    exposure: 9_000,
  },
  {
    id: "sd_chanakyapuri_dhaulakuan",
    name: "Chanakyapuri → Dhaula Kuan",
    corridor: "Lutyens' Delhi",
    from: "chanakyapuri",
    to: "dhaulakuan",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.32,
    drainQuality: 0.72,
    impervious: 0.74,
    exposure: 11_000,
  },
  {
    id: "sd_chanakyapuri_indiagate",
    name: "Chanakyapuri → India Gate",
    corridor: "Lutyens' Delhi",
    from: "chanakyapuri",
    to: "indiagate",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.3,
    drainQuality: 0.74,
    impervious: 0.7,
    majorDrainId: "kushak",
    majorDrainDistanceM: 600,
    exposure: 10_000,
  },
  {
    id: "sd_motibagh_sarojini",
    name: "Moti Bagh → Sarojini Nagar",
    corridor: "South Delhi",
    from: "motibagh",
    to: "sarojini",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.4,
    drainQuality: 0.66,
    impervious: 0.82,
    exposure: 8_500,
  },

  /* ══ Central Delhi ═════════════════════════════════════════════════════ */
  {
    id: "cn_cp_minto",
    name: "Minto Road · Connaught Place → Minto Bridge",
    corridor: "Central Delhi",
    from: "cp",
    to: "minto",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    underpass: true,
    catchment: 0.96,
    drainQuality: 0.2,
    impervious: 0.95,
    majorDrainId: "civillines",
    majorDrainDistanceM: 400,
    pumpStations: 2,
    basementParking: 7,
    exposure: 24_000,
    history: [
      { date: "2023-07-09", depthCm: 186, durationHr: 16, disruptionHr: 26 },
      { date: "2024-06-28", depthCm: 172, durationHr: 14, disruptionHr: 22 },
      { date: "2025-07-27", depthCm: 138, durationHr: 11, disruptionHr: 18 },
    ],
    facilities: ["Minto Bridge underpass", "Connaught Place basements"],
  },
  {
    id: "cn_minto_ndls",
    name: "Minto Bridge → New Delhi Railway Station",
    corridor: "Central Delhi",
    from: "minto",
    to: "ndls",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.82,
    drainQuality: 0.34,
    impervious: 0.94,
    majorDrainId: "civillines",
    majorDrainDistanceM: 500,
    exposure: 22_000,
    history: [{ date: "2024-06-28", depthCm: 63, durationHr: 9, disruptionHr: 14 }],
    facilities: ["New Delhi railway station"],
  },
  {
    id: "cn_cp_ndls",
    name: "Connaught Place → New Delhi Railway Station",
    corridor: "Central Delhi",
    from: "cp",
    to: "ndls",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.6,
    drainQuality: 0.52,
    impervious: 0.94,
    basementParking: 11,
    exposure: 20_000,
  },
  {
    id: "cn_cp_jhandewalan",
    name: "Connaught Place → Jhandewalan",
    corridor: "Central Delhi",
    from: "cp",
    to: "jhandewalan",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.62,
    drainQuality: 0.5,
    impervious: 0.93,
    exposure: 15_000,
  },
  {
    id: "cn_jhandewalan_karolbagh",
    name: "Jhandewalan → Karol Bagh",
    corridor: "Central Delhi",
    from: "jhandewalan",
    to: "karolbagh",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.74,
    drainQuality: 0.4,
    impervious: 0.94,
    basementParking: 8,
    exposure: 18_000,
    history: [
      { date: "2023-07-09", depthCm: 68, durationHr: 11, disruptionHr: 16 },
      { date: "2025-07-27", depthCm: 46, durationHr: 7, disruptionHr: 10 },
    ],
    facilities: ["Karol Bagh market basements"],
  },
  {
    id: "cn_cp_indiagate",
    name: "Connaught Place → India Gate",
    corridor: "Lutyens' Delhi",
    from: "cp",
    to: "indiagate",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.38,
    drainQuality: 0.7,
    impervious: 0.8,
    majorDrainId: "kushak",
    majorDrainDistanceM: 800,
    exposure: 13_000,
  },
  {
    id: "cn_indiagate_ito",
    name: "India Gate → ITO",
    corridor: "Central Delhi",
    from: "indiagate",
    to: "ito",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.66,
    drainQuality: 0.48,
    impervious: 0.88,
    floodplain: 0.3,
    exposure: 17_000,
  },
  {
    id: "cn_ito_delhigate",
    name: "Bahadur Shah Zafar Marg · ITO → Delhi Gate",
    corridor: "Central Delhi",
    from: "ito",
    to: "delhigate",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.8,
    drainQuality: 0.36,
    impervious: 0.92,
    floodplain: 0.42,
    majorDrainId: "civillines",
    majorDrainDistanceM: 250,
    basementParking: 6,
    exposure: 21_000,
    history: [
      { date: "2023-07-13", depthCm: 74, durationHr: 34, disruptionHr: 46 },
      { date: "2024-06-28", depthCm: 48, durationHr: 8, disruptionHr: 13 },
    ],
    facilities: ["Tilak Bridge", "ITO metro"],
  },
  {
    id: "cn_delhigate_redfort",
    name: "Delhi Gate → Red Fort",
    corridor: "Old Delhi",
    from: "delhigate",
    to: "redfort",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.78,
    drainQuality: 0.34,
    impervious: 0.93,
    floodplain: 0.4,
    majorDrainId: "civillines",
    majorDrainDistanceM: 200,
    exposure: 19_000,
    history: [{ date: "2023-07-13", depthCm: 82, durationHr: 40, disruptionHr: 52 }],
  },
  {
    id: "cn_redfort_chandnichowk",
    name: "Red Fort → Chandni Chowk",
    corridor: "Old Delhi",
    from: "redfort",
    to: "chandnichowk",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 30,
    catchment: 0.74,
    drainQuality: 0.36,
    impervious: 0.95,
    exposure: 20_000,
    history: [{ date: "2024-06-28", depthCm: 52, durationHr: 8, disruptionHr: 12 }],
  },
  {
    id: "cn_chandnichowk_kashmeregate",
    name: "Chandni Chowk → Kashmere Gate",
    corridor: "Old Delhi",
    from: "chandnichowk",
    to: "kashmeregate",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.76,
    drainQuality: 0.36,
    impervious: 0.93,
    majorDrainId: "civillines",
    majorDrainDistanceM: 300,
    exposure: 18_000,
  },
  {
    id: "cn_ndls_chandnichowk",
    name: "New Delhi Station → Chandni Chowk",
    corridor: "Old Delhi",
    from: "ndls",
    to: "chandnichowk",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.7,
    drainQuality: 0.42,
    impervious: 0.94,
    exposure: 17_000,
  },
  {
    id: "cn_karolbagh_patelnagar",
    name: "Karol Bagh → Patel Nagar",
    corridor: "Central Delhi",
    from: "karolbagh",
    to: "patelnagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.66,
    drainQuality: 0.48,
    impervious: 0.9,
    exposure: 13_000,
  },
  {
    id: "cn_patelnagar_zakhira",
    name: "Patel Nagar → Zakhira",
    corridor: "Central Delhi",
    from: "patelnagar",
    to: "zakhira",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.8,
    drainQuality: 0.34,
    impervious: 0.9,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 350,
    exposure: 14_000,
  },

  /* ══ North Delhi ═══════════════════════════════════════════════════════ */
  {
    id: "nr_kashmeregate_civillines",
    name: "Kashmere Gate → Civil Lines",
    corridor: "North Delhi",
    from: "kashmeregate",
    to: "civillines",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.68,
    drainQuality: 0.46,
    impervious: 0.86,
    floodplain: 0.35,
    majorDrainId: "civillines",
    majorDrainDistanceM: 250,
    exposure: 14_000,
  },
  {
    id: "nr_tishazari_kashmeregate",
    name: "Tis Hazari → Kashmere Gate",
    corridor: "North Delhi",
    from: "tishazari",
    to: "kashmeregate",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.72,
    drainQuality: 0.42,
    impervious: 0.9,
    exposure: 12_000,
  },
  {
    id: "nr_tishazari_civillines",
    name: "Tis Hazari → Civil Lines",
    corridor: "North Delhi",
    from: "tishazari",
    to: "civillines",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.64,
    drainQuality: 0.5,
    impervious: 0.87,
    exposure: 10_000,
  },
  {
    id: "nr_civillines_gtbnagar",
    name: "Civil Lines → GTB Nagar",
    corridor: "North Delhi",
    from: "civillines",
    to: "gtbnagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.56,
    drainQuality: 0.54,
    impervious: 0.85,
    exposure: 12_000,
    facilities: ["Delhi University North Campus"],
  },
  {
    id: "nr_gtbnagar_mukherjeenagar",
    name: "GTB Nagar → Mukherjee Nagar",
    corridor: "North Delhi",
    from: "gtbnagar",
    to: "mukherjeenagar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.88,
    drainQuality: 0.26,
    impervious: 0.92,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 900,
    basementParking: 12,
    exposure: 21_000,
    history: [
      { date: "2023-07-09", depthCm: 97, durationHr: 18, disruptionHr: 27 },
      { date: "2024-06-28", depthCm: 84, durationHr: 15, disruptionHr: 23 },
      { date: "2025-07-27", depthCm: 66, durationHr: 12, disruptionHr: 18 },
    ],
    facilities: ["Coaching-centre basements", "Batra Cinema junction"],
  },
  {
    id: "nr_mukherjeenagar_modeltown",
    name: "Mukherjee Nagar → Model Town",
    corridor: "North Delhi",
    from: "mukherjeenagar",
    to: "modeltown",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.76,
    drainQuality: 0.38,
    impervious: 0.89,
    exposure: 14_000,
  },
  {
    id: "nr_modeltown_azadpur",
    name: "Model Town → Azadpur",
    corridor: "North Delhi",
    from: "modeltown",
    to: "azadpur",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.8,
    drainQuality: 0.34,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 400,
    exposure: 15_000,
  },
  {
    id: "nr_azadpur_jahangirpuri",
    name: "GT Karnal Road · Azadpur → Jahangirpuri",
    corridor: "GT Karnal Road",
    from: "azadpur",
    to: "jahangirpuri",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.82,
    drainQuality: 0.32,
    impervious: 0.89,
    majorDrainId: "supplementary",
    majorDrainDistanceM: 150,
    exposure: 20_000,
    history: [{ date: "2024-06-28", depthCm: 72, durationHr: 12, disruptionHr: 18 }],
  },
  {
    id: "nr_jahangirpuri_rohini",
    name: "Jahangirpuri → Rohini Sector 18",
    corridor: "North-West Delhi",
    from: "jahangirpuri",
    to: "rohini",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.62,
    drainQuality: 0.52,
    impervious: 0.86,
    majorDrainId: "supplementary",
    majorDrainDistanceM: 600,
    exposure: 15_000,
  },
  {
    id: "nr_rohini_pitampura",
    name: "Rohini → Pitampura",
    corridor: "North-West Delhi",
    from: "rohini",
    to: "pitampura",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.5,
    drainQuality: 0.6,
    impervious: 0.85,
    exposure: 13_000,
  },
  {
    id: "nr_mukarba_burari",
    name: "Mukarba Chowk → Burari",
    corridor: "North Delhi",
    from: "mukarba",
    to: "burari",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.76,
    drainQuality: 0.36,
    impervious: 0.82,
    floodplain: 0.55,
    exposure: 13_000,
  },
  {
    id: "nr_burari_wazirabad",
    name: "Burari → Wazirabad",
    corridor: "North Delhi",
    from: "burari",
    to: "wazirabad",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.84,
    drainQuality: 0.3,
    impervious: 0.78,
    floodplain: 0.92,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 250,
    exposure: 16_000,
    history: [{ date: "2023-07-13", depthCm: 158, durationHr: 96, disruptionHr: 110 }],
    facilities: ["Yamuna floodplain settlements"],
  },

  /* ══ West Delhi ════════════════════════════════════════════════════════ */
  {
    id: "wd_punjabibagh_rajourigarden",
    name: "Punjabi Bagh → Rajouri Garden",
    corridor: "West Delhi",
    from: "punjabibagh",
    to: "rajourigarden",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.66,
    drainQuality: 0.48,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 500,
    basementParking: 6,
    exposure: 16_000,
  },
  {
    id: "wd_rajourigarden_tilaknagar",
    name: "Najafgarh Road · Rajouri Garden → Tilak Nagar",
    corridor: "Najafgarh Road",
    from: "rajourigarden",
    to: "tilaknagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.76,
    drainQuality: 0.4,
    impervious: 0.9,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 300,
    exposure: 17_000,
  },
  {
    id: "wd_tilaknagar_janakpuri",
    name: "Najafgarh Road · Tilak Nagar → Janakpuri",
    corridor: "Najafgarh Road",
    from: "tilaknagar",
    to: "janakpuri",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.78,
    drainQuality: 0.38,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 280,
    exposure: 16_000,
    history: [{ date: "2024-06-28", depthCm: 54, durationHr: 9, disruptionHr: 13 }],
  },
  {
    id: "wd_janakpuri_uttamnagar",
    name: "Najafgarh Road · Janakpuri → Uttam Nagar",
    corridor: "Najafgarh Road",
    from: "janakpuri",
    to: "uttamnagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.84,
    drainQuality: 0.32,
    impervious: 0.9,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 200,
    exposure: 18_000,
    history: [
      { date: "2023-07-09", depthCm: 78, durationHr: 14, disruptionHr: 21 },
      { date: "2025-07-27", depthCm: 58, durationHr: 10, disruptionHr: 15 },
    ],
  },
  {
    id: "wd_uttamnagar_najafgarh",
    name: "Najafgarh Road · Uttam Nagar → Najafgarh",
    corridor: "Najafgarh Road",
    from: "uttamnagar",
    to: "najafgarh",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.93,
    drainQuality: 0.24,
    impervious: 0.82,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 90,
    pumpStations: 2,
    exposure: 20_000,
    history: [
      { date: "2023-07-09", depthCm: 124, durationHr: 34, disruptionHr: 46 },
      { date: "2024-06-28", depthCm: 96, durationHr: 26, disruptionHr: 36 },
      { date: "2025-07-27", depthCm: 88, durationHr: 22, disruptionHr: 31 },
    ],
    facilities: ["Najafgarh drain", "Najafgarh Jheel catchment"],
  },
  {
    id: "wd_najafgarh_dwarka",
    name: "Najafgarh → Dwarka",
    corridor: "West Delhi",
    from: "najafgarh",
    to: "dwarka",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.74,
    drainQuality: 0.44,
    impervious: 0.76,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 700,
    exposure: 13_000,
  },
  {
    id: "wd_janakpuri_dwarka",
    name: "Janakpuri → Dwarka Sector 21",
    corridor: "West Delhi",
    from: "janakpuri",
    to: "dwarka",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.56,
    drainQuality: 0.58,
    impervious: 0.84,
    exposure: 14_000,
  },
  {
    id: "wd_dwarka_igi",
    name: "Dwarka → IGI Airport",
    corridor: "West Delhi",
    from: "dwarka",
    to: "igi",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 70,
    catchment: 0.48,
    drainQuality: 0.62,
    impervious: 0.83,
    exposure: 12_000,
  },
  {
    id: "wd_dwarka_palam",
    name: "Dwarka → Palam",
    corridor: "West Delhi",
    from: "dwarka",
    to: "palam",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.62,
    drainQuality: 0.52,
    impervious: 0.84,
    exposure: 11_000,
  },
  {
    id: "wd_punjabibagh_peeragarhi",
    name: "Rohtak Road · Punjabi Bagh → Peeragarhi",
    corridor: "Rohtak Road",
    from: "punjabibagh",
    to: "peeragarhi",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.8,
    drainQuality: 0.36,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 180,
    exposure: 19_000,
    history: [{ date: "2023-07-09", depthCm: 66, durationHr: 12, disruptionHr: 18 }],
  },
  {
    id: "wd_peeragarhi_nangloi",
    name: "Rohtak Road · Peeragarhi → Nangloi",
    corridor: "Rohtak Road",
    from: "peeragarhi",
    to: "nangloi",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.86,
    drainQuality: 0.3,
    impervious: 0.88,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 120,
    constructionObstruction: true,
    exposure: 21_000,
    history: [
      { date: "2023-07-09", depthCm: 89, durationHr: 17, disruptionHr: 25 },
      { date: "2024-06-28", depthCm: 74, durationHr: 14, disruptionHr: 21 },
      { date: "2025-07-27", depthCm: 61, durationHr: 11, disruptionHr: 16 },
    ],
  },
  {
    id: "wd_nangloi_mundka",
    name: "Rohtak Road · Nangloi → Mundka",
    corridor: "Rohtak Road",
    from: "nangloi",
    to: "mundka",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.7,
    drainQuality: 0.42,
    impervious: 0.84,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 450,
    exposure: 15_000,
  },
  {
    id: "wd_naraina_rajourigarden",
    name: "Naraina → Rajouri Garden",
    corridor: "West Delhi",
    from: "naraina",
    to: "rajourigarden",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.68,
    drainQuality: 0.48,
    impervious: 0.88,
    exposure: 11_000,
  },
  {
    id: "wd_motinagar_punjabibagh",
    name: "Moti Nagar → Punjabi Bagh",
    corridor: "West Delhi",
    from: "motinagar",
    to: "punjabibagh",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.74,
    drainQuality: 0.42,
    impervious: 0.89,
    majorDrainId: "najafgarh",
    majorDrainDistanceM: 260,
    exposure: 11_000,
  },

  /* ══ Trans-Yamuna / East Delhi ═════════════════════════════════════════ */
  {
    id: "ey_ito_laxminagar",
    name: "Vikas Marg · ITO → Laxmi Nagar",
    corridor: "Vikas Marg",
    from: "ito",
    to: "laxminagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.84,
    drainQuality: 0.32,
    impervious: 0.91,
    floodplain: 0.68,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 220,
    basementParking: 9,
    exposure: 26_000,
    history: [
      { date: "2023-07-13", depthCm: 108, durationHr: 58, disruptionHr: 72 },
      { date: "2024-06-28", depthCm: 56, durationHr: 10, disruptionHr: 16 },
      { date: "2025-07-27", depthCm: 49, durationHr: 9, disruptionHr: 14 },
    ],
    facilities: ["ITO bridge", "Laxmi Nagar market basements"],
  },
  {
    id: "ey_laxminagar_preetvihar",
    name: "Vikas Marg · Laxmi Nagar → Preet Vihar",
    corridor: "Vikas Marg",
    from: "laxminagar",
    to: "preetvihar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.76,
    drainQuality: 0.4,
    impervious: 0.9,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 350,
    exposure: 18_000,
  },
  {
    id: "ey_preetvihar_karkardooma",
    name: "Vikas Marg · Preet Vihar → Karkardooma",
    corridor: "Vikas Marg",
    from: "preetvihar",
    to: "karkardooma",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.78,
    drainQuality: 0.38,
    impervious: 0.9,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 200,
    exposure: 17_000,
    history: [{ date: "2024-06-28", depthCm: 51, durationHr: 9, disruptionHr: 14 }],
  },
  {
    id: "ey_karkardooma_anandvihar",
    name: "Karkardooma → Anand Vihar",
    corridor: "East Delhi",
    from: "karkardooma",
    to: "anandvihar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.8,
    drainQuality: 0.36,
    impervious: 0.9,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 260,
    exposure: 20_000,
    history: [{ date: "2025-07-27", depthCm: 58, durationHr: 10, disruptionHr: 16 }],
    facilities: ["Anand Vihar ISBT", "Anand Vihar railway terminal"],
  },
  {
    id: "ey_rajghat_geetacolony",
    name: "Geeta Colony Bridge · Rajghat → Geeta Colony",
    corridor: "East Delhi",
    from: "rajghat",
    to: "geetacolony",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.9,
    drainQuality: 0.26,
    impervious: 0.87,
    floodplain: 0.86,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 150,
    pumpStations: 2,
    exposure: 22_000,
    history: [
      { date: "2023-07-13", depthCm: 152, durationHr: 82, disruptionHr: 96 },
      { date: "2024-06-28", depthCm: 68, durationHr: 13, disruptionHr: 19 },
      { date: "2025-07-27", depthCm: 74, durationHr: 15, disruptionHr: 22 },
    ],
    facilities: ["Geeta Colony bridge", "Yamuna floodplain"],
  },
  {
    id: "ey_geetacolony_laxminagar",
    name: "Geeta Colony → Laxmi Nagar",
    corridor: "East Delhi",
    from: "geetacolony",
    to: "laxminagar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.86,
    drainQuality: 0.28,
    impervious: 0.89,
    floodplain: 0.6,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 120,
    exposure: 17_000,
    history: [{ date: "2023-07-13", depthCm: 116, durationHr: 64, disruptionHr: 78 }],
  },
  {
    id: "ey_kashmeregate_shastripark",
    name: "GT Road · Kashmere Gate → Shastri Park",
    corridor: "GT Road",
    from: "kashmeregate",
    to: "shastripark",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.86,
    drainQuality: 0.3,
    impervious: 0.86,
    floodplain: 0.88,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 130,
    exposure: 21_000,
    history: [{ date: "2023-07-13", depthCm: 164, durationHr: 92, disruptionHr: 108 }],
    facilities: ["Old Iron Bridge (Loha Pul)", "Yamuna floodplain"],
  },
  {
    id: "ey_shastripark_seelampur",
    name: "GT Road · Shastri Park → Seelampur",
    corridor: "GT Road",
    from: "shastripark",
    to: "seelampur",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.82,
    drainQuality: 0.32,
    impervious: 0.88,
    floodplain: 0.62,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 300,
    exposure: 19_000,
    history: [{ date: "2023-07-13", depthCm: 94, durationHr: 48, disruptionHr: 60 }],
  },
  {
    id: "ey_seelampur_yamunavihar",
    name: "Loni Road · Seelampur → Yamuna Vihar",
    corridor: "Loni Road",
    from: "seelampur",
    to: "yamunavihar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.88,
    drainQuality: 0.26,
    impervious: 0.9,
    floodplain: 0.7,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 180,
    exposure: 20_000,
    history: [
      { date: "2023-07-13", depthCm: 128, durationHr: 70, disruptionHr: 84 },
      { date: "2024-06-28", depthCm: 62, durationHr: 12, disruptionHr: 18 },
    ],
  },
  {
    id: "ey_seelampur_shahdara",
    name: "Seelampur → Shahdara",
    corridor: "East Delhi",
    from: "seelampur",
    to: "shahdara",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.78,
    drainQuality: 0.36,
    impervious: 0.9,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 160,
    exposure: 16_000,
  },
  {
    id: "ey_shahdara_karkardooma",
    name: "Shahdara → Karkardooma",
    corridor: "East Delhi",
    from: "shahdara",
    to: "karkardooma",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.74,
    drainQuality: 0.4,
    impervious: 0.89,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 220,
    exposure: 13_000,
  },
  {
    id: "ey_wazirabad_signaturebridge",
    name: "Wazirabad → Signature Bridge",
    corridor: "East Delhi",
    from: "wazirabad",
    to: "signaturebridge",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.84,
    drainQuality: 0.34,
    impervious: 0.8,
    floodplain: 0.95,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 60,
    exposure: 15_000,
    history: [{ date: "2023-07-13", depthCm: 176, durationHr: 104, disruptionHr: 120 }],
  },
  {
    id: "ey_signaturebridge_yamunavihar",
    name: "Signature Bridge → Yamuna Vihar",
    corridor: "East Delhi",
    from: "signaturebridge",
    to: "yamunavihar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.8,
    drainQuality: 0.38,
    impervious: 0.84,
    floodplain: 0.72,
    exposure: 14_000,
  },
  {
    id: "ey_pragati_akshardham",
    name: "NH-9 · Pragati Maidan → Akshardham",
    corridor: "NH-9 (Delhi–Meerut)",
    from: "pragati",
    to: "akshardham",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.82,
    drainQuality: 0.4,
    impervious: 0.88,
    floodplain: 0.8,
    majorDrainId: "yamuna",
    majorDrainDistanceM: 140,
    exposure: 24_000,
    history: [{ date: "2023-07-13", depthCm: 138, durationHr: 72, disruptionHr: 86 }],
    facilities: ["Nizamuddin bridge", "Yamuna floodplain"],
  },
  {
    id: "ey_akshardham_laxminagar",
    name: "Akshardham → Laxmi Nagar",
    corridor: "East Delhi",
    from: "akshardham",
    to: "laxminagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.8,
    drainQuality: 0.38,
    impervious: 0.89,
    floodplain: 0.66,
    majorDrainId: "shahdara",
    majorDrainDistanceM: 280,
    exposure: 17_000,
  },
  {
    id: "ey_akshardham_mayurvihar",
    name: "NH-9 · Akshardham → Mayur Vihar",
    corridor: "NH-9 (Delhi–Meerut)",
    from: "akshardham",
    to: "mayurvihar",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.78,
    drainQuality: 0.42,
    impervious: 0.87,
    floodplain: 0.74,
    exposure: 21_000,
    history: [{ date: "2023-07-13", depthCm: 112, durationHr: 60, disruptionHr: 74 }],
  },
  {
    id: "ey_mayurvihar_noida18",
    name: "Mayur Vihar → Noida Sector 18",
    corridor: "Noida Link Road",
    from: "mayurvihar",
    to: "noida18",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.72,
    drainQuality: 0.46,
    impervious: 0.86,
    floodplain: 0.5,
    exposure: 18_000,
  },
  {
    id: "ey_anandvihar_gazipur",
    name: "Anand Vihar → Ghazipur",
    corridor: "NH-9 (Delhi–Meerut)",
    from: "anandvihar",
    to: "gazipur",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.72,
    drainQuality: 0.44,
    impervious: 0.87,
    exposure: 18_000,
  },
  {
    id: "ey_gazipur_noida18",
    name: "Ghazipur → Noida Sector 18",
    corridor: "Noida Link Road",
    from: "gazipur",
    to: "noida18",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.68,
    drainQuality: 0.48,
    impervious: 0.86,
    exposure: 15_000,
  },
];
