import type { CityMeta, MetroStation, RoadClass } from "../types";

/**
 * Bengaluru road network seed.
 *
 * ─── On the provenance of this data ──────────────────────────────────────────
 * Junctions, corridors and metro stations are real and geocoded to within a few
 * hundred metres. Segment geometry is a straight-line approximation between
 * junction centroids except where waypoints are given, so this is a *risk
 * graph*, not a survey-grade road centreline dataset.
 *
 * Flood history entries are an **illustrative seed** assembled from widely
 * reported waterlogging hotspots. Dates and depths are approximations for
 * demonstration — they are not an official BBMP or BWSSB record, and the
 * provenance attached to every segment says so. Wiring this to a real municipal
 * incident feed means replacing this one file.
 *
 * Elevations are seeded from published topography and then refined at runtime by
 * the Copernicus digital elevation model where that API is reachable.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const BENGALURU: CityMeta = {
  id: "bengaluru",
  name: "Bengaluru",
  country: "India",
  center: { lat: 12.9716, lng: 77.5946 },
  bounds: [12.83, 77.46, 13.06, 77.78],
  timezone: "Asia/Kolkata",
  monsoonMonths: [5, 6, 7, 8, 9, 10, 11],
  elevationRangeM: [860, 935],
};

/** Long-run monthly rainfall normals in mm, index 0 = January. */
export const BENGALURU_MONTHLY_NORMAL_MM = [
  2, 5, 12, 46, 120, 82, 110, 137, 195, 180, 65, 15,
];

/**
 * Rainfall sampling grid.
 *
 * Eight cells across the metropolitan area. Convective storms here are routinely
 * 15 km across, so one centroid reading would badly misrepresent the east while
 * describing the west.
 */
export const BENGALURU_WEATHER_GRID = [
  { lat: 13.035, lng: 77.597 }, // Hebbal — north
  { lat: 13.028, lng: 77.52 }, // Peenya — north-west
  { lat: 12.977, lng: 77.573 }, // Majestic — centre
  { lat: 12.978, lng: 77.641 }, // Indiranagar — centre-east
  { lat: 13.005, lng: 77.696 }, // KR Puram — east
  { lat: 12.945, lng: 77.7 }, // Marathahalli — south-east
  { lat: 12.917, lng: 77.623 }, // Silk Board — south
  { lat: 12.925, lng: 77.53 }, // Banashankari — south-west
];

/* -------------------------------------------------------------------------- */
/*  Junctions                                                                 */
/* -------------------------------------------------------------------------- */

export interface SeedNode {
  id: string;
  name: string;
  lat: number;
  lng: number;
  /** Metres above sea level, seeded from published topography. */
  elevationM: number;
  ward: string;
  metro?: { station: string; line: string; walkM: number };
}

export const BENGALURU_NODES: SeedNode[] = [
  // North
  { id: "hebbal", name: "Hebbal Flyover", lat: 13.0358, lng: 77.597, elevationM: 902, ward: "Hebbal" },
  { id: "mekhri", name: "Mekhri Circle", lat: 13.0128, lng: 77.58, elevationM: 918, ward: "Sanjaynagar" },
  { id: "sankey", name: "Sankey Road", lat: 13.003, lng: 77.579, elevationM: 924, ward: "Malleswaram" },
  { id: "nagawara", name: "Nagawara Junction", lat: 13.043, lng: 77.621, elevationM: 898, ward: "Nagawara" },
  { id: "hennur", name: "Hennur Cross", lat: 13.033, lng: 77.641, elevationM: 902, ward: "Hennur" },
  { id: "kalyannagar", name: "Kalyan Nagar", lat: 13.023, lng: 77.64, elevationM: 900, ward: "Banaswadi" },
  { id: "jalahalli", name: "Jalahalli Cross", lat: 13.043, lng: 77.546, elevationM: 908, ward: "Jalahalli" },
  { id: "yeshwanthpur", name: "Yeshwanthpur Circle", lat: 13.0246, lng: 77.55, elevationM: 916, ward: "Yeshwanthpur", metro: { station: "Yeshwanthpur", line: "Green", walkM: 250 } },
  { id: "peenya", name: "Peenya Junction", lat: 13.029, lng: 77.519, elevationM: 903, ward: "Peenya", metro: { station: "Peenya", line: "Green", walkM: 300 } },

  // West
  { id: "rajajinagar", name: "Rajajinagar", lat: 12.991, lng: 77.552, elevationM: 921, ward: "Rajajinagar", metro: { station: "Rajajinagar", line: "Green", walkM: 400 } },
  { id: "vijayanagar", name: "Vijayanagar", lat: 12.972, lng: 77.532, elevationM: 906, ward: "Vijayanagar", metro: { station: "Vijayanagar", line: "Purple", walkM: 300 } },
  { id: "sumanahalli", name: "Sumanahalli Junction", lat: 12.993, lng: 77.529, elevationM: 898, ward: "Sumanahalli" },
  { id: "nayandahalli", name: "Nayandahalli Junction", lat: 12.942, lng: 77.523, elevationM: 884, ward: "Nayandahalli", metro: { station: "Nayandahalli", line: "Purple", walkM: 300 } },
  { id: "mysoreroad", name: "Mysore Road Junction", lat: 12.945, lng: 77.535, elevationM: 890, ward: "Deepanjali Nagar", metro: { station: "Mysore Road", line: "Purple", walkM: 350 } },
  { id: "kengeri", name: "Kengeri", lat: 12.908, lng: 77.483, elevationM: 872, ward: "Kengeri", metro: { station: "Kengeri", line: "Purple", walkM: 500 } },

  // Central business district
  { id: "majestic", name: "Kempegowda / Majestic", lat: 12.977, lng: 77.573, elevationM: 914, ward: "Gandhinagar", metro: { station: "Nadaprabhu Kempegowda", line: "Purple / Green", walkM: 120 } },
  { id: "shivajinagar", name: "Shivajinagar", lat: 12.986, lng: 77.605, elevationM: 918, ward: "Shivajinagar" },
  { id: "mgroad", name: "MG Road", lat: 12.975, lng: 77.606, elevationM: 921, ward: "Shantala Nagar", metro: { station: "MG Road", line: "Purple", walkM: 150 } },
  { id: "richmond", name: "Richmond Circle", lat: 12.96, lng: 77.596, elevationM: 920, ward: "Sampangiram Nagar" },
  { id: "lalbagh", name: "Lalbagh West Gate", lat: 12.9507, lng: 77.5848, elevationM: 916, ward: "Sudhama Nagar", metro: { station: "Lalbagh", line: "Green", walkM: 400 } },
  { id: "ulsoor", name: "Ulsoor / Trinity", lat: 12.982, lng: 77.62, elevationM: 906, ward: "Ulsoor", metro: { station: "Trinity", line: "Purple", walkM: 500 } },

  // South-central
  { id: "dairycircle", name: "Dairy Circle", lat: 12.937, lng: 77.596, elevationM: 904, ward: "Lakkasandra", metro: { station: "Jayadeva Hospital", line: "Yellow", walkM: 700 } },
  { id: "jayanagar", name: "Jayanagar 4th Block", lat: 12.925, lng: 77.583, elevationM: 910, ward: "Jayanagar", metro: { station: "Jayanagar", line: "Green", walkM: 450 } },
  { id: "jpnagar", name: "JP Nagar", lat: 12.907, lng: 77.585, elevationM: 905, ward: "JP Nagar", metro: { station: "JP Nagar", line: "Green", walkM: 400 } },
  { id: "banashankari", name: "Banashankari", lat: 12.925, lng: 77.567, elevationM: 902, ward: "Banashankari", metro: { station: "Banashankari", line: "Green", walkM: 300 } },
  { id: "kanakapura", name: "Konanakunte Cross", lat: 12.895, lng: 77.556, elevationM: 890, ward: "Konanakunte", metro: { station: "Konanakunte Cross", line: "Green", walkM: 350 } },

  // South
  { id: "btm", name: "BTM Layout", lat: 12.9166, lng: 77.6101, elevationM: 897, ward: "BTM Layout", metro: { station: "BTM Layout", line: "Yellow", walkM: 350 } },
  { id: "silkboard", name: "Central Silk Board", lat: 12.9172, lng: 77.6228, elevationM: 893, ward: "Bommanahalli", metro: { station: "Central Silk Board", line: "Yellow", walkM: 250 } },
  { id: "bommanahalli", name: "Bommanahalli", lat: 12.9, lng: 77.622, elevationM: 894, ward: "Bommanahalli", metro: { station: "Bommanahalli", line: "Yellow", walkM: 300 } },
  { id: "ecity", name: "Electronic City", lat: 12.845, lng: 77.66, elevationM: 908, ward: "Electronic City", metro: { station: "Electronic City", line: "Yellow", walkM: 500 } },
  { id: "hsr", name: "HSR Layout", lat: 12.911, lng: 77.641, elevationM: 890, ward: "HSR Layout" },

  // Koramangala valley
  { id: "koramangala", name: "Koramangala (Sony World)", lat: 12.9352, lng: 77.6245, elevationM: 896, ward: "Koramangala" },
  { id: "ejipura", name: "Ejipura Junction", lat: 12.943, lng: 77.628, elevationM: 898, ward: "Jogupalya" },
  { id: "agara", name: "Agara Junction", lat: 12.923, lng: 77.639, elevationM: 892, ward: "Agara" },
  { id: "domlur", name: "Domlur Flyover", lat: 12.961, lng: 77.638, elevationM: 903, ward: "Domlur" },
  { id: "indiranagar", name: "Indiranagar 100ft Road", lat: 12.9784, lng: 77.6408, elevationM: 912, ward: "Indiranagar", metro: { station: "Indiranagar", line: "Purple", walkM: 350 } },

  // East — Outer Ring Road and beyond
  { id: "iblur", name: "Iblur Junction", lat: 12.92, lng: 77.672, elevationM: 882, ward: "Bellandur" },
  { id: "bellandur", name: "Bellandur / Devarabisanahalli", lat: 12.935, lng: 77.687, elevationM: 879, ward: "Bellandur" },
  { id: "kaadubeesanahalli", name: "Kaadubeesanahalli", lat: 12.942, lng: 77.696, elevationM: 883, ward: "Varthur" },
  { id: "marathahalli", name: "Marathahalli Bridge", lat: 12.9569, lng: 77.7011, elevationM: 888, ward: "Marathahalli" },
  { id: "mahadevapura", name: "Mahadevapura", lat: 12.991, lng: 77.689, elevationM: 886, ward: "Mahadevapura" },
  { id: "krpuram", name: "KR Puram Hanging Bridge", lat: 13.008, lng: 77.696, elevationM: 884, ward: "KR Puram", metro: { station: "Krishnarajapura", line: "Purple", walkM: 400 } },
  { id: "tinfactory", name: "Tin Factory", lat: 12.999, lng: 77.666, elevationM: 888, ward: "Baiyappanahalli" },
  { id: "byappanahalli", name: "Byappanahalli", lat: 12.993, lng: 77.652, elevationM: 895, ward: "Baiyappanahalli", metro: { station: "Baiyappanahalli", line: "Purple", walkM: 300 } },
  { id: "kasturinagar", name: "Kasturi Nagar", lat: 13.009, lng: 77.66, elevationM: 894, ward: "Banaswadi" },
  { id: "murugeshpalya", name: "Murugeshpalya", lat: 12.96, lng: 77.656, elevationM: 900, ward: "Konena Agrahara" },
  { id: "kundalahalli", name: "Kundalahalli Gate", lat: 12.96, lng: 77.715, elevationM: 892, ward: "Hoodi", metro: { station: "Kundalahalli", line: "Purple", walkM: 350 } },
  { id: "whitefield", name: "Whitefield / Hope Farm", lat: 12.9698, lng: 77.75, elevationM: 890, ward: "Whitefield" },
  { id: "kadugodi", name: "Kadugodi", lat: 12.995, lng: 77.76, elevationM: 900, ward: "Kadugodi", metro: { station: "Whitefield (Kadugodi)", line: "Purple", walkM: 400 } },
  { id: "varthur", name: "Varthur Kodi", lat: 12.94, lng: 77.74, elevationM: 885, ward: "Varthur" },
  { id: "sarjapur", name: "Kaikondrahalli (Sarjapur Rd)", lat: 12.908, lng: 77.687, elevationM: 886, ward: "Bellandur" },
];

export const BENGALURU_METRO: MetroStation[] = BENGALURU_NODES.filter(
  (n) => n.metro,
).map((n) => ({
  id: `metro_${n.id}`,
  name: n.metro!.station,
  line: n.metro!.line,
  at: { lat: n.lat, lng: n.lng },
}));

/* -------------------------------------------------------------------------- */
/*  Segments                                                                  */
/* -------------------------------------------------------------------------- */

export interface SeedFloodRecord {
  date: string;
  depthCm: number;
  durationHr: number;
}

export interface SeedSegment {
  id: string;
  name: string;
  corridor: string;
  from: string;
  to: string;
  roadClass: RoadClass;
  lanes: number;
  speedLimitKph: number;
  /** Real road bends, traced with a couple of intermediate points. */
  waypoints?: { lat: number; lng: number }[];
  /** Road dips under a rail line or flyover — water has nowhere to go. */
  underpass?: boolean;
  /** 0..1 override for how much upstream area drains onto this road. */
  catchment?: number;
  /** 0..1 — how well the storm drain network here actually performs. */
  drainQuality?: number;
  /** 0..1 sealed surface fraction of the contributing catchment. */
  impervious?: number;
  history?: SeedFloodRecord[];
  /** People directly affected when this segment goes under. */
  exposure?: number;
  facilities?: string[];
}

const HIGH_EXPOSURE = 24_000;

export const BENGALURU_SEGMENTS: SeedSegment[] = [
  /* ── Outer Ring Road, eastern arc ──────────────────────────────────────── */
  {
    id: "orr_hebbal_nagawara",
    name: "ORR · Hebbal → Nagawara",
    corridor: "Outer Ring Road (East)",
    from: "hebbal",
    to: "nagawara",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.78,
    drainQuality: 0.45,
    impervious: 0.86,
    exposure: 18_000,
    history: [
      { date: "2022-09-05", depthCm: 34, durationHr: 7 },
      { date: "2024-10-16", depthCm: 22, durationHr: 4 },
    ],
    facilities: ["Manyata Tech Park"],
  },
  {
    id: "orr_nagawara_hennur",
    name: "ORR · Nagawara → Hennur",
    corridor: "Outer Ring Road (East)",
    from: "nagawara",
    to: "hennur",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.62,
    drainQuality: 0.55,
    impervious: 0.8,
    exposure: 12_000,
  },
  {
    id: "orr_hennur_kalyannagar",
    name: "ORR · Hennur → Kalyan Nagar",
    corridor: "Outer Ring Road (East)",
    from: "hennur",
    to: "kalyannagar",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.58,
    drainQuality: 0.58,
    impervious: 0.78,
    exposure: 11_000,
  },
  {
    id: "orr_kalyannagar_kasturinagar",
    name: "ORR · Kalyan Nagar → Kasturi Nagar",
    corridor: "Outer Ring Road (East)",
    from: "kalyannagar",
    to: "kasturinagar",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.66,
    drainQuality: 0.5,
    impervious: 0.82,
    exposure: 13_000,
  },
  {
    id: "orr_kasturinagar_krpuram",
    name: "ORR · Kasturi Nagar → KR Puram",
    corridor: "Outer Ring Road (East)",
    from: "kasturinagar",
    to: "krpuram",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.84,
    drainQuality: 0.38,
    impervious: 0.88,
    exposure: 21_000,
    history: [
      { date: "2022-09-05", depthCm: 46, durationHr: 11 },
      { date: "2023-10-21", depthCm: 28, durationHr: 5 },
      { date: "2025-05-19", depthCm: 39, durationHr: 8 },
    ],
  },
  {
    id: "orr_krpuram_mahadevapura",
    name: "ORR · KR Puram → Mahadevapura",
    corridor: "Outer Ring Road (East)",
    from: "krpuram",
    to: "mahadevapura",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.88,
    drainQuality: 0.34,
    impervious: 0.9,
    exposure: HIGH_EXPOSURE,
    history: [
      { date: "2022-09-05", depthCm: 52, durationHr: 14 },
      { date: "2024-05-21", depthCm: 31, durationHr: 6 },
      { date: "2025-05-19", depthCm: 44, durationHr: 9 },
    ],
    facilities: ["ITPL corridor", "KR Puram railway station"],
  },
  {
    id: "orr_mahadevapura_marathahalli",
    name: "ORR · Mahadevapura → Marathahalli",
    corridor: "Outer Ring Road (East)",
    from: "mahadevapura",
    to: "marathahalli",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.8,
    drainQuality: 0.42,
    impervious: 0.89,
    exposure: 20_000,
    history: [{ date: "2022-09-05", depthCm: 37, durationHr: 8 }],
  },
  {
    id: "orr_marathahalli_kaadubeesanahalli",
    name: "ORR · Marathahalli → Kaadubeesanahalli",
    corridor: "Outer Ring Road (East)",
    from: "marathahalli",
    to: "kaadubeesanahalli",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.86,
    drainQuality: 0.36,
    impervious: 0.91,
    exposure: 22_000,
    history: [
      { date: "2022-09-05", depthCm: 58, durationHr: 16 },
      { date: "2024-10-16", depthCm: 33, durationHr: 6 },
    ],
    facilities: ["Embassy TechVillage"],
  },
  {
    id: "orr_kaadubeesanahalli_bellandur",
    name: "ORR · Kaadubeesanahalli → Bellandur",
    corridor: "Outer Ring Road (East)",
    from: "kaadubeesanahalli",
    to: "bellandur",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.94,
    drainQuality: 0.3,
    impervious: 0.92,
    exposure: HIGH_EXPOSURE,
    history: [
      { date: "2022-09-05", depthCm: 71, durationHr: 22 },
      { date: "2023-09-12", depthCm: 29, durationHr: 5 },
      { date: "2024-10-16", depthCm: 41, durationHr: 9 },
      { date: "2025-05-19", depthCm: 55, durationHr: 13 },
    ],
    facilities: ["Bellandur lake overflow channel"],
  },
  {
    id: "orr_bellandur_iblur",
    name: "ORR · Bellandur → Iblur",
    corridor: "Outer Ring Road (East)",
    from: "bellandur",
    to: "iblur",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.92,
    drainQuality: 0.32,
    impervious: 0.9,
    exposure: 23_000,
    history: [
      { date: "2022-09-05", depthCm: 64, durationHr: 19 },
      { date: "2024-10-16", depthCm: 36, durationHr: 7 },
    ],
  },
  {
    id: "orr_iblur_agara",
    name: "ORR · Iblur → Agara",
    corridor: "Outer Ring Road (East)",
    from: "iblur",
    to: "agara",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.79,
    drainQuality: 0.44,
    impervious: 0.87,
    exposure: 17_000,
    history: [{ date: "2022-09-05", depthCm: 33, durationHr: 6 }],
  },
  {
    id: "orr_agara_silkboard",
    name: "ORR · Agara → Central Silk Board",
    corridor: "Outer Ring Road (East)",
    from: "agara",
    to: "silkboard",
    roadClass: "ring",
    lanes: 8,
    speedLimitKph: 50,
    catchment: 0.85,
    drainQuality: 0.35,
    impervious: 0.93,
    exposure: HIGH_EXPOSURE,
    history: [
      { date: "2022-09-05", depthCm: 48, durationHr: 12 },
      { date: "2023-10-21", depthCm: 26, durationHr: 4 },
      { date: "2025-05-19", depthCm: 37, durationHr: 7 },
    ],
    facilities: ["Silk Board interchange"],
  },

  /* ── Outer Ring Road, western arc ──────────────────────────────────────── */
  {
    id: "orr_hebbal_jalahalli",
    name: "ORR · Hebbal → Jalahalli",
    corridor: "Outer Ring Road (West)",
    from: "hebbal",
    to: "jalahalli",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.5,
    drainQuality: 0.62,
    impervious: 0.74,
    exposure: 9_000,
  },
  {
    id: "orr_jalahalli_peenya",
    name: "ORR · Jalahalli → Peenya",
    corridor: "Outer Ring Road (West)",
    from: "jalahalli",
    to: "peenya",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.6,
    drainQuality: 0.48,
    impervious: 0.8,
    exposure: 11_000,
    history: [{ date: "2024-05-21", depthCm: 41, durationHr: 5 }],
  },
  {
    id: "orr_peenya_sumanahalli",
    name: "ORR · Peenya → Sumanahalli",
    corridor: "Outer Ring Road (West)",
    from: "peenya",
    to: "sumanahalli",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    catchment: 0.55,
    drainQuality: 0.56,
    impervious: 0.78,
    exposure: 10_000,
  },
  {
    id: "orr_sumanahalli_nayandahalli",
    name: "ORR · Sumanahalli → Nayandahalli",
    corridor: "Outer Ring Road (West)",
    from: "sumanahalli",
    to: "nayandahalli",
    roadClass: "ring",
    lanes: 6,
    speedLimitKph: 60,
    underpass: true,
    catchment: 0.72,
    drainQuality: 0.4,
    impervious: 0.83,
    exposure: 14_000,
    history: [
      { date: "2022-09-05", depthCm: 43, durationHr: 6 },
      { date: "2024-05-21", depthCm: 38, durationHr: 5 },
    ],
    facilities: ["Sumanahalli underpass"],
  },
  {
    id: "mys_nayandahalli_kengeri",
    name: "Mysore Road · Nayandahalli → Kengeri",
    corridor: "Mysore Road",
    from: "nayandahalli",
    to: "kengeri",
    roadClass: "highway",
    lanes: 6,
    speedLimitKph: 70,
    catchment: 0.68,
    drainQuality: 0.5,
    impervious: 0.7,
    exposure: 12_000,
    history: [{ date: "2022-09-05", depthCm: 30, durationHr: 5 }],
  },

  /* ── Hosur Road ────────────────────────────────────────────────────────── */
  {
    id: "hos_silkboard_bommanahalli",
    name: "Hosur Road · Silk Board → Bommanahalli",
    corridor: "Hosur Road",
    from: "silkboard",
    to: "bommanahalli",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 60,
    catchment: 0.74,
    drainQuality: 0.46,
    impervious: 0.89,
    exposure: 19_000,
    history: [{ date: "2023-10-21", depthCm: 27, durationHr: 4 }],
  },
  {
    id: "hos_bommanahalli_ecity",
    name: "Hosur Road · Bommanahalli → Electronic City",
    corridor: "Hosur Road",
    from: "bommanahalli",
    to: "ecity",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 80,
    catchment: 0.46,
    drainQuality: 0.64,
    impervious: 0.76,
    exposure: 15_000,
    facilities: ["Electronic City elevated corridor"],
  },
  {
    id: "hos_btm_silkboard",
    name: "Hosur Road · BTM → Silk Board",
    corridor: "Hosur Road",
    from: "btm",
    to: "silkboard",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.7,
    drainQuality: 0.48,
    impervious: 0.88,
    exposure: 13_000,
  },

  /* ── Sarjapur Road ─────────────────────────────────────────────────────── */
  {
    id: "sar_agara_iblur",
    name: "Sarjapur Road · Agara → Iblur",
    corridor: "Sarjapur Road",
    from: "agara",
    to: "iblur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.82,
    drainQuality: 0.36,
    impervious: 0.88,
    exposure: 16_000,
    history: [
      { date: "2022-09-05", depthCm: 45, durationHr: 10 },
      { date: "2025-05-19", depthCm: 32, durationHr: 6 },
    ],
  },
  {
    id: "sar_iblur_sarjapur",
    name: "Sarjapur Road · Iblur → Kaikondrahalli",
    corridor: "Sarjapur Road",
    from: "iblur",
    to: "sarjapur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.76,
    drainQuality: 0.42,
    impervious: 0.85,
    exposure: 14_000,
    history: [{ date: "2024-10-16", depthCm: 28, durationHr: 5 }],
  },
  {
    id: "sar_hsr_sarjapur",
    name: "HSR Layout → Kaikondrahalli",
    corridor: "Sarjapur Road",
    from: "hsr",
    to: "sarjapur",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.64,
    drainQuality: 0.52,
    impervious: 0.82,
    exposure: 9_000,
  },
  {
    id: "sar_hsr_agara",
    name: "HSR Layout → Agara",
    corridor: "HSR Layout",
    from: "hsr",
    to: "agara",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.7,
    drainQuality: 0.5,
    impervious: 0.84,
    exposure: 8_500,
    history: [{ date: "2022-09-05", depthCm: 39, durationHr: 9 }],
  },
  {
    id: "sar_hsr_silkboard",
    name: "HSR Layout → Silk Board",
    corridor: "HSR Layout",
    from: "hsr",
    to: "silkboard",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.72,
    drainQuality: 0.47,
    impervious: 0.86,
    exposure: 9_500,
  },

  /* ── Whitefield ────────────────────────────────────────────────────────── */
  {
    id: "wf_marathahalli_kundalahalli",
    name: "Whitefield Road · Marathahalli → Kundalahalli",
    corridor: "Whitefield Road",
    from: "marathahalli",
    to: "kundalahalli",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.66,
    drainQuality: 0.52,
    impervious: 0.85,
    exposure: 13_000,
  },
  {
    id: "wf_kundalahalli_whitefield",
    name: "Whitefield Road · Kundalahalli → Hope Farm",
    corridor: "Whitefield Road",
    from: "kundalahalli",
    to: "whitefield",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.58,
    drainQuality: 0.58,
    impervious: 0.8,
    exposure: 11_000,
  },
  {
    id: "wf_whitefield_kadugodi",
    name: "Whitefield Road · Hope Farm → Kadugodi",
    corridor: "Whitefield Road",
    from: "whitefield",
    to: "kadugodi",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.48,
    drainQuality: 0.6,
    impervious: 0.72,
    exposure: 8_000,
  },
  {
    id: "wf_marathahalli_varthur",
    name: "Varthur Road · Marathahalli → Varthur",
    corridor: "Varthur Road",
    from: "marathahalli",
    to: "varthur",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.9,
    drainQuality: 0.28,
    impervious: 0.8,
    exposure: 12_000,
    history: [
      { date: "2022-09-05", depthCm: 62, durationHr: 20 },
      { date: "2024-10-16", depthCm: 44, durationHr: 11 },
    ],
    facilities: ["Varthur lake"],
  },
  {
    id: "wf_varthur_whitefield",
    name: "Varthur → Hope Farm",
    corridor: "Varthur Road",
    from: "varthur",
    to: "whitefield",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.7,
    drainQuality: 0.44,
    impervious: 0.74,
    exposure: 7_500,
  },

  /* ── Old Madras Road ───────────────────────────────────────────────────── */
  {
    id: "omr_ulsoor_byappanahalli",
    name: "Old Madras Road · Ulsoor → Byappanahalli",
    corridor: "Old Madras Road",
    from: "ulsoor",
    to: "byappanahalli",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.54,
    drainQuality: 0.6,
    impervious: 0.83,
    exposure: 10_000,
  },
  {
    id: "omr_byappanahalli_tinfactory",
    name: "Old Madras Road · Byappanahalli → Tin Factory",
    corridor: "Old Madras Road",
    from: "byappanahalli",
    to: "tinfactory",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.8,
    drainQuality: 0.38,
    impervious: 0.88,
    exposure: 17_000,
    history: [
      { date: "2022-09-05", depthCm: 42, durationHr: 9 },
      { date: "2023-10-21", depthCm: 25, durationHr: 4 },
    ],
  },
  {
    id: "omr_tinfactory_krpuram",
    name: "Old Madras Road · Tin Factory → KR Puram",
    corridor: "Old Madras Road",
    from: "tinfactory",
    to: "krpuram",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    underpass: true,
    catchment: 0.87,
    drainQuality: 0.32,
    impervious: 0.89,
    exposure: 21_000,
    history: [
      { date: "2022-09-05", depthCm: 55, durationHr: 15 },
      { date: "2024-05-21", depthCm: 36, durationHr: 7 },
      { date: "2025-05-19", depthCm: 47, durationHr: 10 },
    ],
    facilities: ["KR Puram railway underpass"],
  },
  {
    id: "omr_indiranagar_byappanahalli",
    name: "Indiranagar → Byappanahalli",
    corridor: "Old Madras Road",
    from: "indiranagar",
    to: "byappanahalli",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.46,
    drainQuality: 0.64,
    impervious: 0.82,
    exposure: 7_000,
  },

  /* ── Old Airport Road ──────────────────────────────────────────────────── */
  {
    id: "oar_domlur_murugeshpalya",
    name: "Old Airport Road · Domlur → Murugeshpalya",
    corridor: "Old Airport Road",
    from: "domlur",
    to: "murugeshpalya",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.5,
    drainQuality: 0.62,
    impervious: 0.85,
    exposure: 11_000,
  },
  {
    id: "oar_murugeshpalya_marathahalli",
    name: "Old Airport Road · Murugeshpalya → Marathahalli",
    corridor: "Old Airport Road",
    from: "murugeshpalya",
    to: "marathahalli",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.72,
    drainQuality: 0.46,
    impervious: 0.87,
    exposure: 16_000,
    history: [{ date: "2022-09-05", depthCm: 35, durationHr: 7 }],
  },

  /* ── Inner Ring Road and Koramangala valley ────────────────────────────── */
  {
    id: "irr_koramangala_domlur",
    name: "Inner Ring Road · Koramangala → Domlur",
    corridor: "Inner Ring Road",
    from: "koramangala",
    to: "domlur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.68,
    drainQuality: 0.5,
    impervious: 0.88,
    exposure: 14_000,
  },
  {
    id: "irr_domlur_indiranagar",
    name: "Inner Ring Road · Domlur → Indiranagar",
    corridor: "Inner Ring Road",
    from: "domlur",
    to: "indiranagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.44,
    drainQuality: 0.66,
    impervious: 0.84,
    exposure: 10_000,
  },
  {
    id: "irr_indiranagar_ulsoor",
    name: "Indiranagar → Ulsoor",
    corridor: "Inner Ring Road",
    from: "indiranagar",
    to: "ulsoor",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.42,
    drainQuality: 0.66,
    impervious: 0.82,
    exposure: 8_000,
  },
  {
    id: "kor_koramangala_ejipura",
    name: "Koramangala → Ejipura",
    corridor: "Koramangala",
    from: "koramangala",
    to: "ejipura",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.83,
    drainQuality: 0.33,
    impervious: 0.9,
    exposure: 15_000,
    history: [
      { date: "2022-09-05", depthCm: 49, durationHr: 12 },
      { date: "2024-10-16", depthCm: 31, durationHr: 6 },
    ],
  },
  {
    id: "kor_ejipura_domlur",
    name: "Ejipura → Domlur",
    corridor: "Koramangala",
    from: "ejipura",
    to: "domlur",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.6,
    drainQuality: 0.54,
    impervious: 0.86,
    exposure: 9_000,
  },
  {
    id: "kor_koramangala_silkboard",
    name: "80 Feet Road · Koramangala → Silk Board",
    corridor: "Koramangala",
    from: "koramangala",
    to: "silkboard",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.86,
    drainQuality: 0.32,
    impervious: 0.91,
    exposure: 18_000,
    history: [
      { date: "2022-09-05", depthCm: 53, durationHr: 13 },
      { date: "2023-09-12", depthCm: 24, durationHr: 4 },
      { date: "2025-05-19", depthCm: 40, durationHr: 8 },
    ],
  },
  {
    id: "kor_koramangala_agara",
    name: "Koramangala → Agara",
    corridor: "Koramangala",
    from: "koramangala",
    to: "agara",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.75,
    drainQuality: 0.44,
    impervious: 0.87,
    exposure: 10_000,
  },
  {
    id: "kor_koramangala_dairycircle",
    name: "Koramangala → Dairy Circle",
    corridor: "Koramangala",
    from: "koramangala",
    to: "dairycircle",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.56,
    drainQuality: 0.58,
    impervious: 0.85,
    exposure: 8_500,
  },
  {
    id: "kor_koramangala_btm",
    name: "Koramangala → BTM Layout",
    corridor: "Koramangala",
    from: "koramangala",
    to: "btm",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.78,
    drainQuality: 0.4,
    impervious: 0.88,
    exposure: 11_000,
    history: [{ date: "2022-09-05", depthCm: 38, durationHr: 8 }],
  },

  /* ── Central business district ─────────────────────────────────────────── */
  {
    id: "cbd_mgroad_shivajinagar",
    name: "MG Road → Shivajinagar",
    corridor: "CBD",
    from: "mgroad",
    to: "shivajinagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.3,
    drainQuality: 0.72,
    impervious: 0.9,
    exposure: 9_000,
  },
  {
    id: "cbd_shivajinagar_majestic",
    name: "Shivajinagar → Majestic",
    corridor: "CBD",
    from: "shivajinagar",
    to: "majestic",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.4,
    drainQuality: 0.64,
    impervious: 0.92,
    exposure: 14_000,
  },
  {
    id: "cbd_majestic_richmond",
    name: "Majestic → Richmond Circle",
    corridor: "CBD",
    from: "majestic",
    to: "richmond",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 40,
    catchment: 0.38,
    drainQuality: 0.68,
    impervious: 0.91,
    exposure: 12_000,
  },
  {
    id: "cbd_richmond_mgroad",
    name: "Richmond Circle → MG Road",
    corridor: "CBD",
    from: "richmond",
    to: "mgroad",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.28,
    drainQuality: 0.74,
    impervious: 0.9,
    exposure: 8_000,
  },
  {
    id: "cbd_richmond_lalbagh",
    name: "Richmond Circle → Lalbagh",
    corridor: "CBD",
    from: "richmond",
    to: "lalbagh",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.34,
    drainQuality: 0.7,
    impervious: 0.82,
    exposure: 7_500,
  },
  {
    id: "cbd_lalbagh_dairycircle",
    name: "Lalbagh → Dairy Circle",
    corridor: "CBD",
    from: "lalbagh",
    to: "dairycircle",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.52,
    drainQuality: 0.6,
    impervious: 0.84,
    exposure: 8_000,
  },
  {
    id: "cbd_mgroad_ulsoor",
    name: "MG Road → Ulsoor",
    corridor: "CBD",
    from: "mgroad",
    to: "ulsoor",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.44,
    drainQuality: 0.64,
    impervious: 0.86,
    exposure: 7_000,
  },
  {
    id: "cbd_shivajinagar_sankey",
    name: "Shivajinagar → Sankey Road",
    corridor: "CBD",
    from: "shivajinagar",
    to: "sankey",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.26,
    drainQuality: 0.76,
    impervious: 0.78,
    exposure: 6_500,
  },
  {
    id: "cbd_majestic_rajajinagar",
    name: "Okalipuram · Majestic → Rajajinagar",
    corridor: "CBD",
    from: "majestic",
    to: "rajajinagar",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 40,
    underpass: true,
    catchment: 0.68,
    drainQuality: 0.42,
    impervious: 0.92,
    exposure: 13_000,
    history: [
      { date: "2022-09-05", depthCm: 40, durationHr: 6 },
      { date: "2024-05-21", depthCm: 33, durationHr: 4 },
    ],
    facilities: ["Okalipuram underpass"],
  },

  /* ── North ─────────────────────────────────────────────────────────────── */
  {
    id: "n_sankey_mekhri",
    name: "Sankey Road → Mekhri Circle",
    corridor: "Sankey Road",
    from: "sankey",
    to: "mekhri",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.24,
    drainQuality: 0.78,
    impervious: 0.7,
    exposure: 6_000,
  },
  {
    id: "n_mekhri_hebbal",
    name: "Bellary Road · Mekhri → Hebbal",
    corridor: "Bellary Road",
    from: "mekhri",
    to: "hebbal",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.46,
    drainQuality: 0.64,
    impervious: 0.8,
    exposure: 15_000,
    facilities: ["Airport corridor"],
  },
  {
    id: "n_mekhri_yeshwanthpur",
    name: "Mekhri Circle → Yeshwanthpur",
    corridor: "CNR Rao Circle",
    from: "mekhri",
    to: "yeshwanthpur",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.36,
    drainQuality: 0.7,
    impervious: 0.8,
    exposure: 9_000,
  },
  {
    id: "n_yeshwanthpur_peenya",
    name: "Tumkur Road · Yeshwanthpur → Peenya",
    corridor: "Tumkur Road",
    from: "yeshwanthpur",
    to: "peenya",
    roadClass: "highway",
    lanes: 8,
    speedLimitKph: 70,
    catchment: 0.52,
    drainQuality: 0.58,
    impervious: 0.84,
    exposure: 14_000,
  },
  {
    id: "n_yeshwanthpur_rajajinagar",
    name: "Yeshwanthpur → Rajajinagar",
    corridor: "Dr Rajkumar Road",
    from: "yeshwanthpur",
    to: "rajajinagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.34,
    drainQuality: 0.7,
    impervious: 0.85,
    exposure: 8_000,
  },
  {
    id: "n_jalahalli_yeshwanthpur",
    name: "Jalahalli → Yeshwanthpur",
    corridor: "Tumkur Road",
    from: "jalahalli",
    to: "yeshwanthpur",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 50,
    catchment: 0.4,
    drainQuality: 0.66,
    impervious: 0.78,
    exposure: 7_500,
  },

  /* ── West ──────────────────────────────────────────────────────────────── */
  {
    id: "w_rajajinagar_vijayanagar",
    name: "Rajajinagar → Vijayanagar",
    corridor: "West Bengaluru",
    from: "rajajinagar",
    to: "vijayanagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.44,
    drainQuality: 0.64,
    impervious: 0.86,
    exposure: 8_500,
  },
  {
    id: "w_vijayanagar_nayandahalli",
    name: "Vijayanagar → Nayandahalli",
    corridor: "West Bengaluru",
    from: "vijayanagar",
    to: "nayandahalli",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.7,
    drainQuality: 0.46,
    impervious: 0.85,
    exposure: 10_000,
    history: [{ date: "2022-09-05", depthCm: 36, durationHr: 6 }],
  },
  {
    id: "w_majestic_mysoreroad",
    name: "Mysore Road · Majestic → Deepanjali Nagar",
    corridor: "Mysore Road",
    from: "majestic",
    to: "mysoreroad",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.6,
    drainQuality: 0.54,
    impervious: 0.89,
    exposure: 13_000,
  },
  {
    id: "w_mysoreroad_nayandahalli",
    name: "Mysore Road · Deepanjali Nagar → Nayandahalli",
    corridor: "Mysore Road",
    from: "mysoreroad",
    to: "nayandahalli",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.74,
    drainQuality: 0.44,
    impervious: 0.86,
    exposure: 11_000,
    history: [{ date: "2024-05-21", depthCm: 29, durationHr: 5 }],
  },

  /* ── South ─────────────────────────────────────────────────────────────── */
  {
    id: "s_banashankari_jayanagar",
    name: "Banashankari → Jayanagar",
    corridor: "South Bengaluru",
    from: "banashankari",
    to: "jayanagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.36,
    drainQuality: 0.7,
    impervious: 0.83,
    exposure: 8_000,
  },
  {
    id: "s_jayanagar_dairycircle",
    name: "Jayanagar → Dairy Circle",
    corridor: "South Bengaluru",
    from: "jayanagar",
    to: "dairycircle",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.48,
    drainQuality: 0.62,
    impervious: 0.85,
    exposure: 8_500,
  },
  {
    id: "s_jayanagar_jpnagar",
    name: "Jayanagar → JP Nagar",
    corridor: "South Bengaluru",
    from: "jayanagar",
    to: "jpnagar",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.42,
    drainQuality: 0.66,
    impervious: 0.84,
    exposure: 7_500,
  },
  {
    id: "s_jpnagar_btm",
    name: "JP Nagar → BTM Layout",
    corridor: "South Bengaluru",
    from: "jpnagar",
    to: "btm",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.66,
    drainQuality: 0.5,
    impervious: 0.87,
    exposure: 9_500,
  },
  {
    id: "s_jpnagar_kanakapura",
    name: "Kanakapura Road · JP Nagar → Konanakunte",
    corridor: "Kanakapura Road",
    from: "jpnagar",
    to: "kanakapura",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.5,
    drainQuality: 0.6,
    impervious: 0.8,
    exposure: 10_000,
  },
  {
    id: "s_kanakapura_banashankari",
    name: "Konanakunte → Banashankari",
    corridor: "Kanakapura Road",
    from: "kanakapura",
    to: "banashankari",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.44,
    drainQuality: 0.64,
    impervious: 0.78,
    exposure: 7_000,
  },
  {
    id: "s_banashankari_mysoreroad",
    name: "Banashankari → Deepanjali Nagar",
    corridor: "Outer Ring Road (South)",
    from: "banashankari",
    to: "mysoreroad",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.58,
    drainQuality: 0.56,
    impervious: 0.8,
    exposure: 7_000,
  },
  {
    id: "s_lalbagh_jayanagar",
    name: "Lalbagh → Jayanagar",
    corridor: "South Bengaluru",
    from: "lalbagh",
    to: "jayanagar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.4,
    drainQuality: 0.68,
    impervious: 0.8,
    exposure: 6_500,
  },
  {
    id: "s_btm_jayanagar",
    name: "BTM Layout → Jayanagar",
    corridor: "South Bengaluru",
    from: "btm",
    to: "jayanagar",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.62,
    drainQuality: 0.54,
    impervious: 0.86,
    exposure: 8_000,
  },
  {
    id: "s_btm_bommanahalli",
    name: "BTM Layout → Bommanahalli",
    corridor: "South Bengaluru",
    from: "btm",
    to: "bommanahalli",
    roadClass: "collector",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.68,
    drainQuality: 0.5,
    impervious: 0.87,
    exposure: 8_500,
  },
  {
    id: "s_dairycircle_btm",
    name: "Bannerghatta Road · Dairy Circle → BTM",
    corridor: "Bannerghatta Road",
    from: "dairycircle",
    to: "btm",
    roadClass: "arterial",
    lanes: 6,
    speedLimitKph: 50,
    catchment: 0.72,
    drainQuality: 0.46,
    impervious: 0.88,
    exposure: 15_000,
    history: [{ date: "2023-10-21", depthCm: 26, durationHr: 4 }],
    facilities: ["Jayadeva cardiology hospital"],
  },
  {
    id: "s_dairycircle_richmond",
    name: "Dairy Circle → Richmond Circle",
    corridor: "Bannerghatta Road",
    from: "dairycircle",
    to: "richmond",
    roadClass: "arterial",
    lanes: 4,
    speedLimitKph: 40,
    catchment: 0.46,
    drainQuality: 0.64,
    impervious: 0.87,
    exposure: 9_000,
  },
];
